### ISSUE TITLE
Additional comments while saving the data can't be cleared

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#1]
When we click on the save button, we need to add the comments  which can't cleared in automation and in the frontend.

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/726306d1-2647-4ca7-bb93-0cbea566ff2d)

**Comment by Adnan-shariff** [comment]
When attempting to manually clear the previously filled comments in the comment section the issue persists as the previous comments cannot be cleared.

**Comment by AnkitExcelerate** [comment]
Working as expected
