### ISSUE TITLE
Incorrect spelling in error messgae (Evaluate).

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#10]
When assigned application to user outside his org code, then we get this error. Chnage the Spelling of **Evaluate**.

Steps
1. Go to Assign app to specific user
2. Upload csv with apps outside user org code
3. error text

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/8ba3a4e9-320c-4edb-84a8-f27793a1ffb6)

**Comment by NavnathGunjal7** [comment]
@akashexes there are some issues in csv upload also with respect to org code casing resolve that one also

**Comment by shivanim11** [comment]
Fixed
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/ceed8663-6591-4584-97f8-6e779779db8f)
