### ISSUE TITLE
hardcoded ug_txt and pg_txt in htmls on top even if you selected 2nd degree as undergrade in report it will show as postgrad

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#101]
**Describe the bug**
1. hardcoded ug_txt and pg_txt in htmls on top even if you selected 2nd degree as undergrade in report it will show as postgrad
2. here in below report 2 degree evaluation is there and 2nd degree is also undergrade so there should be no postgrade in report 

[Derrick John Assabil-cua100825.pdf](https://github.com/Globalshala/Eval-Bridge-bugs/files/15317261/Derrick.John.Assabil-cua100825.pdf)

**Comment by mansi38299** [comment]
degree equivalency and gpa on Top has hardcorded value 
@shivanim11  Please verify all dual degree of HTML of all University 
If there is any issue in any html, Please add those organisation and html name here

**Comment by shivanim11** [comment]
@NavnathGunjal7 
please check this doc to update the HTML
https://docs.google.com/document/d/1O3T5H2UPA6FBn6cYvTsLIdRZXCJiUtP2OtGr5I0U3_M/edit

**Comment by shivanim11** [comment]
Fixed
