### ISSUE TITLE
append 2 Pg_txt based on ug_txt value

### ISSUE THREAD

**Issue by mansi38299** [Globalshala/Eval-Bridge-bugs#104]
Please go through the video to understand the issue

https://drive.google.com/file/d/10VHQMtI8PlWK2YlmxP0Std2R2iv3dAMH/view?usp=sharing

Expected behaviour: 
if we have chose undergraduate and then in second dropdown value contain ( Undergraduate 2, Postgraduate)

**Comment by shivanim11** [comment]
Fixed in dev
