### ISSUE TITLE
My Task Approver: Grade Scale Edit: Unexpected Error "Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#106]
**Describe the bug**
when we click on my task approver and navigate to grade scale edit we are facing an error message"Cannot convert undefined or null to object"

**Scope of the bug**
My task approver > Grade scale edit

**Expected Behavior**
Clicking on a task approver and navigating to grade scale edit should:
Load the grade scale edit page successfully.
Allow users to edit the grade scale settings.

**Actual Behavior**
Clicking on a task approver and navigating to grade scale edit results in the error message "Cannot convert undefined or null to object" instead of loading the edit page.

**Screenshots**
![2024-05-15 18_54_36-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/28cc178b-0938-4014-87ae-1519188bd715)
![issue15april](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/99b136e2-3eff-4c34-8b11-7952fafc4b03)
![2024-05-15 18_47_12-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/b39a49db-a793-4e71-b175-7083fd5cf85c)

**Comment by NavnathGunjal7** [comment]
@Adnan-shariff  please veirfy and close
