### ISSUE TITLE
Send Back To Evaluator Issue: Error Message "Cannot read properties of undefined (reading 'sk')" When clicked on "Send Back to Evaluator"

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#109]
**Describe the bug:**
 When attempting to send an application back to the evaluator, an error message appears, stating "Cannot read properties of undefined (reading 'sk')."

**Scope of the bug:** 
Evaluation> Review> Send Back to Evaluator
This bug affects the functionality of the "Send Back to Evaluator" feature.

**Steps To Reproduce:**
1.Fill the application and Click on send to Next level
2.In review click on Send back to evaluator 

**Expected Behavior:** 
The application should be successfully sent back to the evaluator without any error messages.

**Actual Behavior:** 
An error message "Cannot read properties of undefined (reading 'sk')" is displayed when trying to send an application back to the evaluator.

**Screenshots:**
![2024-05-20 18_06_43-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/5d940d27-a584-4476-8391-f5189bc7577a)
![2024-05-20 18_03_12-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/656fe812-967e-46f2-a4f2-59220f60ab85)

**Comment by ipankajparihar** [comment]
I did not encounter this error but there was error with handleUpdateInTransactItem in //assign to evaluator part

**Comment by shivanim11** [comment]
Fixed
