### ISSUE TITLE
pg_no_process_reason in database how

### ISSUE THREAD

**Issue by mansi38299** [Globalshala/Eval-Bridge-bugs#11]
pg_no_process_reason is attribute which will hold reason when pg transcript in no available 
How come this attribute added in Organisation table

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/79189076/dfea2768-a2e1-4082-9f46-0ffd86d25946)

**Comment by AnkitExcelerate** [comment]
Not reproducible
