### ISSUE TITLE
Application List: Remove "High" Priority Option from Application Priority List

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#110]
**Describe the bug:**
 The application priority list includes the option "High" as a priority level, which is not part of the specified priority levels. 

**Scope of the bug:**
 Application List> priority selection dropdown

**Steps to Reproduce:**
1. Navigate to the application list 
2. priority selection dropdown.
3. Observe the available options in the priority list.

**Expected Behavior:**
 The application priority list should only display two options: "Very Low" and "Critical/Urgent,

**Actual Behavior:**
 The application priority list includes an additional option "High," which is not part of the specified priority levels.

**Screenshots:** 
![2024-05-20 18_44_31-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/c6296a3b-704c-4d1e-b8b6-e837eb78a989)

**Comment by NavnathGunjal7** [comment]
@thirumeni-ram  please check and verify

**Comment by thirumeni-ram** [comment]
here **add confirmation Issue reference is not related**  to this .

**Comment by shivanim11** [comment]
Fixed
getting options as expected
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/40078b1c-ca46-4790-9656-6f6cac1920b8)
