### ISSUE TITLE
GPA Degree and grade should be in one row

### ISSUE THREAD

**Issue by mansi38299** [Globalshala/Eval-Bridge-bugs#114]
In the output here the gpa for both the degrees are aligned on different. We need to have the gpa and letter grade be on same row. 

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/79189076/06e26cde-2837-44ca-b3fe-e60b3771dce3)

We need reduce the space in first column,

**Comment by shivanim11** [comment]
Fixed on Dev
