### ISSUE TITLE
Applications List: Issue in Force Assign of Applications to Evaluators when applied Priority - Critical/Urgent

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#115]
**Describe the bug:**
When an application is not assigned to any evaluator, the system does not automatically assign it to an available evaluator when a priority Critical/Urgent is applied to the application.

**Scope of the bug:** 
Applications list> Apply Priority to a application present in db> Critical/Urgent  

**Steps to reproduce:**
Select applications which are not assigned to any user but presnt in Db.
Apply a priority level - Critical/urgent to the application. 
Observe that the application is not automatically assigned to an available evaluator. 
Priority is updated but its not forced assigned.

**Expected Behavior:** 
When a priority level is applied to an application that is not assigned to any evaluator, the system should automatically assign it to an available evaluator.

**Actual Behavior:** 
When a priority level is applied to an application that is not assigned to any evaluator, the system does not automatically assign it to an available evaluator.

For instance:
cua100507-priority applied Critical/urgent >not assigned
cua100691-priority applied Critical/urgent >not assigned
slu100879-priority applied Critical/urgent >not assigned

Screenshots:
![2024-05-22 11_35_12-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/b4b60df6-bde0-41e9-ace8-c8356a40c1c5)
![2024-05-22 11_34_08-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/c53cb901-9d21-44b5-9c5e-78c6508b552f)
![2024-05-22 11_32_40-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/461e966d-8d37-4cf5-9189-e4f4d1d42a90)
![2024-05-22 14_05_52-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/e86b7dd1-5fd2-451b-b62b-0699ef15435d)

**Comment by kartikatyagi** [comment]
not working as expected 
when we are assigning priority to the appid which are present in database and are not assigned to any user we are getting error and the priority is not changing
**screenshot:** 
![image](https://github.com/user-attachments/assets/91160e1e-1a8a-47d4-aaf6-5aa32ef66ca2)

**Comment by Adnan-shariff** [comment]
when we apply priority for second time its assigning but not at the first time we asssign.
![2024-08-12 14_36_51-Window](https://github.com/user-attachments/assets/7f539077-13a8-4010-bcb5-7359ca18fccb)
![2024-08-12 14_36_29-Window](https://github.com/user-attachments/assets/cb69b850-5f90-40b3-be29-128ec79c1e7f)
![2024-08-12 14_27_45-Window](https://github.com/user-attachments/assets/efe7c38d-f968-4912-b15d-981943ab63cc)

**Comment by Adnan-shariff** [comment]
As per New US Story Requirement: 

**We will only increase the priority of Application 
We will not assign the application to any user**
