### ISSUE TITLE
Applications List: Filter - Inconsistent Display of Duplicate Application IDs

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#116]
**Describe the bug:** 
When filtering the Applications List by application ID, the filter results may inconsistently display the same application ID twice.

**Scope of the bug:** 
Application List> Filter

**Steps to reproduce:**
Navigate to the Applications List.
Click on the Filter button.
In the Filter dialog, search for a specific application ID (e.g. "cua100507").
Observe that the same application ID may appear twice in the filter results, but this behavior is not consistent.

**Expected Behavior:** 
The filter results should always display each application ID only once.

**Actual Behavior:**
The filter results may inconsistently display the same application ID twice, leading to confusion and potential errors in application management.

Screenshots:
![2024-05-20 16_23_46-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/6e4b0f4e-bad8-4ba4-b124-53cb14b34d39)
![2024-05-22 11_32_40-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/0b5cf7f1-1027-4b03-b76b-0fdf591696c5)
![2024-05-22 11_34_08-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/3d7fb65d-5cfb-4782-b1b4-f30ad80d5cef)

**Comment by ipankajparihar** [comment]
In dev env its showing one one appId while searching, its working fine.

**Comment by NavnathGunjal7** [comment]
@Adnan-shariff please test and close

**Comment by Adnan-shariff** [comment]
working as intended .
![2024-06-25 11_37_38-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/f57c43ca-1968-4d38-bdea-9bcd9161d3c7)
![2024-06-25 11_36_40-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/f540094d-8432-469d-9867-da25d27c04cb)
![2024-06-25 11_35_55-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/3a932f17-952a-4020-930d-f3d5d9d51484)
