### ISSUE TITLE
Send back to evaluator - sets priority to 6 in the database instead of 5

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#117]
**Describe the bug:** 
"Send back to evaluator" sets priority to 6 in the database instead of 5 

**Scope of the bug:** 
Evaluation> Send to Next level> Review > Send Back to Evaluator
For instance: 
Appid :
1.slu213265 
2slu9748 

**Expected Behavior:** 
The priority of the application should be set to 5 when it is sent back to the evaluator.

**Actual Behavior:**
The priority of the application is incorrectly set to 6 in the database when it is sent back to the evaluator.

Screenshots:

![2024-05-22 14_54_05-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/b0dd269b-90b4-4a34-ac9c-45bb3b8fb275)
![2024-05-22 14_39_47-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/a7eb9e0e-0075-479f-a2a5-8e55ffcd4885)
![2024-05-22 14_38_38-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/5c3fe727-7ea5-447d-9d85-8e285e4f1933)
![Uploading 2024-05-22 15_02_43-Window.jpg…]()

**Comment by pankajsparihar** [comment]
Priority should be 6
