### ISSUE TITLE
add orgnisation wise emails every where we should able to change emails for specific users with orgs

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#120]
**Describe the bug**
add orgnisation wise emails every where we should able to change emails for specific users with orgs

**To Reproduce**
1. create separate email templates / discuss with Mansi and yash

**Expected behavior**
organisation wise emails should be sent to moderators

**Comment by pankajsparihar** [comment]
USJUNE01 PR raised, this issue will be covered there,

**Comment by shivanim11** [comment]
Fixed
