### ISSUE TITLE
able to send to next level for high school with gpa = 0 / undefined

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#121]
**Describe the bug**
able to send to next level for high school with gpa = 0 / undefined

**To Reproduce**
1. eval any high school data and send to next level able to send to next level

**Expected behavior**
should not able to send to next level when gpa = 0 and it's CBC evaluations

**Comment by mansi38299** [comment]
Verify this issue

**Comment by shivanim11** [comment]
@AnkitExcelerate verify this

**Comment by shivanim11** [comment]
Fixed on Dev
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/3d3c0c53-dd55-4633-a46d-5e40d0811797)
