### ISSUE TITLE
issues in distribution

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#126]
**Describe the bug**
issues in distribution

**To Reproduce**
1. issue in update expression 
2. app id is getting assigned but not moved from eval to in_eval pool --> partial transaction happed pool transaction failed
**Expected behavior**
1. no update expression issue
2. no partial transaction should happen

**Screenshots**

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/108262338/2bfee428-fc11-4312-b455-2eabc8691d5f)

**Comment by shivanim11** [comment]
Fixed on dev. if appid is assigned via distribution then its moving from eval to in_eval
