### ISSUE TITLE
Application Lists: Upload High Prio Applications: if we upload its showing Error "No user has capacity to assign this application"

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#128]
**Describe the bug**
if we upload a Csv file with appid to apply priority it is showing Error "No user has capacity to assign this application" eventhough user have capacity 

**Scope of the bug**
**Application lists> Upload High Prio Applications: CSV file upload** 

**Steps to reproduce**
1.Click on application lists
2.Select Upload High Prio Applications
3.Create a CSV file with app id to apply priority 
please check the csv file attached 
4.click on upload 

**Expected Behavior**
When we upload CSV file priority should be applied.

**Actual Behavior**
It is preventing from applying priority from CSv file upload with an Error message: 

**Screenshots**

![2024-05-30 14_22_31-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/2827eea0-a588-4aea-af7a-b6483ada7404)
![2024-05-30 14_22_06-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/66f4c617-9398-4d10-bb62-f8e729bb90db)
![2024-05-30 14_28_19-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/602da853-d1f2-4ad3-9343-0a67fd2b9bf2)
![2024-05-30 14_27_31-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/51eeeb23-ca50-41e9-92bb-3b97e0ef175d)
![2024-05-30 14_29_32-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/4a6f634d-a70a-441a-b7fe-10d1908719d0)
Csv file :[applistcsv7.csv](https://github.com/Globalshala/Eval-Bridge-bugs/files/15496323/applistcsv7.csv)

**Comment by pankajsparihar** [comment]
its fixed in dev .

**Comment by Adnan-shariff** [comment]
working as intended in dev priority is assigned tested with bulk file too.
![2024-06-07 13_23_20-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/9d020c1a-a640-4cb9-9faa-a4efc3600f82)
[applistcsv78.csv](https://github.com/user-attachments/files/15722032/applistcsv78.csv)
