### ISSUE TITLE
My Team Page- not loading completely and scroll functionality issue and - Issue in Capacity text field 

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#129]
**Describe the bug**
Clicking "My Team" only displays 5 applications.

**Scope of the bug**
My team users loading 

**Steps to Reproduce:**
**Click on Grade scales/application lists/or any other tab from this tab> click on My team** 
Observe that only 5 applications load.
Attempt to scroll down the list.
Verify that scrolling does not load additional users.

**Expected Result:**
All applications users with "My Team" should load and be viewable.
Scrolling down the list should progressively load additional applications.

**Actual Result:**
Only 5 applications load initially.
Scrolling down has no effect on loading additional applications.

![2024-05-30 14_59_52-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/c5cc739e-fd85-4ad8-8614-bd15cea75226)

**Issue 2:** 
Title: Capacity Text Fields Accepting Negative Values

**Describe the bug**
The capacity text fields, intended for positive values only (zero or greater), are accepting negative numbers including -0.1 and below. This can lead to inaccurate data entry and potential issues in calculations or visualizations based on capacity values.

**Scope of the bug**
**My Team update capacity text fields** 

**Steps to Reproduce:**
Click on My team 
Try to update capacity 
Enter a negative value (e.g., -1, -0.5, -00.1) in a capacity text field.
Observe that the negative value is accepted without any error message.

**Expected Behavior:**
These text fields should enforce the entry of positive values only. This could be achieved by:
Disabling negative number entry entirely.
Displaying an error message upon entering a negative value.

**Actual Result:**
Negative values are accepted in the capacity text fields.

Screenshots:
![2024-05-30 15_40_](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/9276ba57-854b-499d-93f9-0dc5948f6674)

![zero zero in capacity is being saved](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/6d9079fa-779e-4a33-be74-39f779cad3c3)
![0 01 being save d](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/4cff04eb-3be0-4f3e-8fdc-96abeea6fb3a)
![-1002](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/9740dc70-00ec-41cf-bcfa-f674cdbb3415)
![-minus 1000 is being saved](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/36326801-6985-4a40-9749-362fdd58f4a1)
![zero zero in capacity is being saved](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/2a6ccc72-40b9-41bf-bed4-df0e67fd3206)
![zero zero in capacity is being saved2](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/57d60bab-8b7d-4d4e-932c-d891bb3f848b)

**Comment by Adnan-shariff** [comment]
Issue 2: is not fixed please check the screenshots attached 


![2024-06-14 18_55_50-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/cb59239c-3d5d-4cf1-b8fa-743dac58664c)
![2024-06-14 18_43_55-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/c920d571-c98e-4227-94ad-4ee83aa476dc)
![2024-06-14 18_43_39-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/035eedf6-2506-4e28-86db-fd800d668488)
![2024-06-14 18_34_57-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/f689db0b-c311-4d3e-8b61-8459852c9808)
![2024-06-14 18_34_28-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/0255fc34-ee9b-4c1f-9d0e-e6052f640151)

**Comment by shivanim11** [comment]
Fixed.
not accepting negative values and scroller is available
