### ISSUE TITLE
issue in import csv for duplicate apps

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#130]
1. if csv file contains duplicate apps it showing error
2. should not get error and import should success full with duplicate apps email

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/108262338/88c13056-126c-42ab-a140-220809818a81)

**Comment by Adnan-shariff** [comment]
working as intended.
if few appids are duplicate 
![2024-06-26 17_32_28-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/0f2b7f6b-abe3-4eb4-86dd-ac52b180ceb9)
![2024-06-26 17_54_50-image (2)](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/b3b758f1-b7ad-4a54-b15a-fc9ccffaa542)



if all appids are duplicate 
![2024-06-26 17_22_47-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/4702cbeb-9a54-415a-afdb-a79009fd5b5f)

![2024-06-26 17_17_02-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/f4fd5de6-d049-49b9-a2cb-76d40668307d)
