### ISSUE TITLE
issue in importing personal_id data

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#131]
**Describe the bug**
issue in importing personal id added data

**To Reproduce**
1. add personal id column in data it should be allowed to update in db

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/108262338/ebe51d6f-e26f-4ce2-a205-1f2c3bfa6591)

**Comment by AnkitExcelerate** [comment]
Working as expected
