### ISSUE TITLE
Application Lists: Upload High Priority Applications/Priority filter button: Showing error "We did not get any response from server!! Try again later"

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#132]
**Describe the bug**
When we try upload an app from CSV file if the appid is not assigned to give priority it shows an error  "We did not get any response from server!! Try again later"

**Scope of the bug**
**Application lists >Upload High Priority Applications>upload an appid which has no evaluator assigned** 

**To Reproduce**
1.Click on Application lists 
2.Click on Upload High priority applications 
3.Upload a file with appid who doesnt have user assigned 

**Expected behavior**
when we upload the appid, it should be uploaded and also priority should be as well as user should be assigned 

**Actual Behavior**
Shows error message "We did not get any response from server!! Try again later"

**Screenshots**
Please check the csv file and screenshot attached
[applistcsv15.csv](https://github.com/user-attachments/files/15529486/applistcsv15.csv)
![2024-06-03 11_15_32-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/56aed39b-7930-431f-9cb9-4f5c10f64b39)
![2024-06-03 11_15_04-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/d0166c00-73c0-4106-b426-4117ebd98e51)
![2024-05-31 18_21_40-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/635e0a79-458a-4f08-b7d5-d817c13c24f3)

**Comment by pankajsparihar** [comment]
this bug is related to Action table in DB and has been fixed in dev

**Comment by Adnan-shariff** [comment]
working as intended hence closing this issue.
![2024-06-12 17_21_52-Cred Eval Bridge](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/22035c54-7251-45be-802f-efd97c6e05d5)
