### ISSUE TITLE
add confirmation dialogue on send to next level

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#134]
1. take confirmation from user when he clicks on send to next level

**Comment by thirumeni-ram** [comment]
Issue -  [https://github.com/Globalshala/Eval-Bridge-bugs/issues/134](https://github.com/Globalshala/Eval-Bridge-bugs/issues/134)

**Comment by thirumeni-ram** [comment]
Here the first reference **Removed High priority option from Application Priority List #110**  is not **Related to this**,
I made a mistake while Adding Comments.

**Comment by thirumeni-ram** [comment]
Here **"Remove High Priority Option"**  is not related to this.

**Comment by shivanim11** [comment]
Fixed on dev

**Comment by shivanim11** [comment]
Fixed
