### ISSUE TITLE
Assign appids to specific user: Insert appid's to database from Organization drive: Assign to the user: shows an error message "We did not get any response from server!! Try again later."

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#135]
**Describe the bug**
After we import we are not able to assign the appids to the user shows an error message "We did not get any response from server!! Try again later."

**Scope of the bug**
Assign appids: import appids in drive > Assign appids to the user 

**Steps to reproduce**
1. Upload app IDs for import in drive 
2. Click on my profile 
3. click on actions 
4. Insert appid's to database from Organization drive
5. Click on Assign appids to specific user tab
6. Attempt to assign uploaded IDs.

**Expected Behavior**
Successful assigning appids to user

**Actual Behavior**
Error message prevents assigning appids to user: "We did not get any response from server!! Try again later."

![2024-06-04 15_46_44-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/61c24a14-24bd-40c4-b707-d63540e118ea)
![2024-06-04 15_37_29-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/6faf52c7-5a9f-4247-b6d3-10310f5c0994)

**Comment by Adnan-shariff** [comment]
![2024-06-04 15_34_04-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/a6f433ad-e599-44c6-a7f6-a3a2ee67f996)

**Comment by Adnan-shariff** [comment]
working as intended no changes required.

**Comment by shivanim11** [comment]
Fixed
