### ISSUE TITLE
issue in only updating evaluator capacity

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#136]
1. remove 0 and and save it it will save null value
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/108262338/4e22f6fe-f5ac-4de2-aee8-65024833cdc5)

**Comment by mansi38299** [comment]
@AnkitExcelerate  Understand exact problem statement from Navnath Like how to reproduce and verify and close this issue

**Comment by MSGlobalShala** [comment]
@NavnathGunjal7 So what should be the expected behaviour according to you?
