### ISSUE TITLE
My Team: Filter button: Unexpected Error:"Pass options.removeUndefinedValues=true to remove undefined values from map/array/set."

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#137]
**Describe the bug**
when we search in my team text field like s or a and hit enter we are seeing an unexpected error 
"Pass options.removeUndefinedValues=true to remove undefined values from map/array/set."

**Scope of the bug**
My Team> Filter button 

**Steps to reproduce**
1.Click on my team 
2.In Filter textfield enter S or A 

**Expected Behavior**
we should be able to fetch users with S or A in thier name/email.

**Actual Behavior**
we are seeing an error message"Pass options.removeUndefinedValues=true to remove undefined values from map/array/set."

**Screenshots**
![2024-06-04 16_52_53-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/44520544-f712-49d0-957e-868350ba7c70)

**Comment by pankajsparihar** [comment]
I did not find any error while testing on dev  and localhost. In preview we are getting the success msg.

**Comment by Adnan-shariff** [comment]
working as intended hence closing this issue .
![2024-06-19 17_36_28-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/80292313-b0d1-4717-91cf-eb230e1e4ea8)
![2024-06-19 17_37_35-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/85df1590-548a-4e39-84ef-1bab522494ed)
