### ISSUE TITLE
Autosave button issue

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#14]
**Describe the bug**
on autosave button there is check box we are seeing. kindly remove this.
**To Reproduce**
1. Go to 'type of evaluation'
2. Click on 'autosave button'
3. See error

**Expected behavior**
check box should not be there.

**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/c0ec5243-37ab-4b15-bdda-0a6cd9439a35)

**Comment by AnkitExcelerate** [comment]
Fixed in dev
