### ISSUE TITLE
Change Auto save,store value in Session Storage

### ISSUE THREAD

**Issue by mansi38299** [Globalshala/Eval-Bridge-bugs#141]
**Describe the bug**
Currently, If Auto save is on, When the user will go from the type of evaluation(By turning off Auto save ) to the Undergrad evaluation page, the Auto save will automatically turn ON.

What do we need to do?
We need to maintain a variable called AutoSave in session storage, which we take value based on user action,
We will be giving preference to that value
If Session storage value doesn't exist, we will be using env value

**Expected behavior**
Auto Save will be remain on or OFF based on User Action

**Comment by NavnathGunjal7** [comment]
@Adnan-shariff  please test and close

**Comment by shivanim11** [comment]
Fixed
