### ISSUE TITLE
getting error while clicking on save button

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#142]
While clicking on save button when all the required  data is filled it's still giving error "Please fill required fields"

Steps - 
1. Type of eval general
2. click on Next 
3. Fill all the required data and click on save button
4. error pop up

Test Data -  slu#1717048419921  ID-ankit@vempower.org

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/793c7790-80aa-4ab2-85d8-39ee562df65c)

**Comment by NavnathGunjal7** [comment]
getting this error in automation as well not able to save data @mansi38299  
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/108262338/86e7af01-cc04-4070-995c-8d134712c2a1)

**Comment by AnkitExcelerate** [comment]
Also when we click on Type of evaluation button after this The UG Scale and all the data below that is deleted and the data on UG Evaluation is saved successfully.

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/daa8479e-af00-4992-bd9d-ecc09873b720)

**Comment by NavnathGunjal7** [comment]
> @NavnathGunjal7  Also when we click on Type of evaluation button after this The UG Scale and all the data below that is deleted and the data on UG Evaluation is saved successfully.
> 
> ![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/daa8479e-af00-4992-bd9d-ecc09873b720)
> 
> ![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/85bf8df3-6fd8-4ae7-9b92-0bbc4ee0ccd8)
> 

Yes I encountered it too

**Comment by shivanim11** [comment]
@AnkitExcelerate please verify it

**Comment by AnkitExcelerate** [comment]
Working in Dev
