### ISSUE TITLE
Start a new app: fill all details click on save shows error message:please fill all required fields 

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#145]
**Describe the bug:**  
After filling all details for a new appid  and clicking save, an error message wrongly asks to fill all required fields.

**Scope of the bug:**  
Evaluation  

**Steps to reproduce:**  
1. Start a new app.
2. Fill all details.
3. Click save.
4. See the error message.

**Expected Behavior:**  
After filling all details, saving should be successfull

**Actual Behavior:**  
Despite filling everything, an error asks to fill all required fields.

**Screenshots:**  
![2024-06-05 17_40_31-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/fbceed01-0ed2-4052-84f6-9265d2e45950)
![2024-06-05 17_38_31-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/936751f2-bfb9-481b-8a25-1f6cbb0e78e2)

![2024-06-05 17_37_56-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/4d63ce0c-a9ea-414b-a952-ec675a3bad40)

**Comment by AnkitExcelerate** [comment]
https://github.com/Globalshala/Eval-Bridge-bugs/issues/142 same issue

**Comment by Adnan-shariff** [comment]
closing as duplicate of #142
