### ISSUE TITLE
Getting error when saving data in cbc page

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#146]
When saving the data in cbc page getting error "input is required/ Internal error"

steps 
1. CBC type of eval
2. cbc page- enter data
3. click save
4. error pop up 

test data -  slu1717056733729   id-ankit@vempower.org

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/7d1c85c6-a6b8-42b1-ae6f-15b9a31a0ead)

**Comment by sl-repo** [comment]
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/114980064/ec0ed33c-efaa-4c00-b35a-e754ac636dd4)

**Comment by AnkitExcelerate** [comment]
The data is getting stored
