### ISSUE TITLE
FastTrack application issues

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#149]
**Describe the bug**
1. added one new attribute in db in import map and trying to upload it in csv file but getting error that its not allowed
2. when we enter cbc data for fastrack application we are not saving first row. if we enter only one record and saved data and going back to cbc page then that record is not there. refer the video to reproduce: 
https://www.loom.com/share/e7fb0e117bbd45b2b2c85fb186e262c3
3. sent to next level from evaluation level for FastTrack appid getting error check attached screenshot
**To Reproduce**
1. Go to 'dynamoDb'
3. add one attribute
4. add it in csv and try to import
5. See error

**Expected behavior**
it should accept the attribute
**Screenshots**
1. 
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/7aa6248b-ea2e-4426-a4fa-9f2ce8a2ece2)
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/a24356f3-e551-4c39-b5b8-874df3ff57aa)
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/0c545641-dab3-4342-9205-c5e56a30802a)
issue3:
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/b48e57e9-e0d4-42e9-b1a7-f0c68c2152bc)

**Comment by MSGlobalShala** [comment]
I have resolved the issue regarding the import CSV
1. https://github.com/Globalshala/credentialEvaluation-Backend/pull/174

**Comment by shivanim11** [comment]
1st issue is resolved
2nd issue not resolved
@pankajsparihar Kindly look into this

**Comment by pankajsparihar** [comment]
for issue 2 PR raised 
https://github.com/Globalshala/Credential-Eval-Frontend/pull/348

**Comment by shivanim11** [comment]
Fixed
