### ISSUE TITLE
preview issue and undefine in college name when not filled

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#15]
**Describe the bug**
preview was not immediately updated undefine in college name when not filled

**To Reproduce**
1. save data on eval page
2. check preview you need to 2 click preview to see current preview

**Expected behavior**
preview should be same as data added and current data preview ... 
there should be no undefined

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AnkitExcelerate** [comment]
Fixed in dev
