### ISSUE TITLE
transcript not loading even file if id recived from backend

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#150]
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/108262338/812df7d2-1768-4d4e-8116-5ede41024e23)

**Comment by mansi38299** [comment]
Please verify and close

**Comment by Adnan-shariff** [comment]
working as intended in both dev and localhost.


please check the screenshot attached .

![2024-06-10 14_03_40-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/a15f4281-d2f7-4200-b226-d0d1240c3b8e)

![2024-06-10 14_02_54-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/5bf6f7ba-e572-485e-8bdf-67f0b3a02765)
