### ISSUE TITLE
master upload invalid keys issues

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#152]
1. if add invalid keys in export map this error will come
2. as there was a space between key
![image (1)](https://github.com/Globalshala/Eval-Bridge-bugs/assets/108262338/d31cc9f6-2a61-471a-8e91-faff917a3983)

**Comment by mansi38299** [comment]
Verify please @shivanim11

**Comment by shivanim11** [comment]
Fixed
