### ISSUE TITLE
Send to next level not workig in review stage

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#153]
The send to next level button is not working and giving error that application  should be in review in progress not review new but the application is in in_rev pool.

steps
1. Evaluation 1 application type cbc for org CUA
2. send it for review
3. click on send to next level button
4. Error Pop up

**AppId**- App#cua416949108         
   **Pool** - Pool#20240312    
           **Id**- ankit@vempower.org

Screenshot - 
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/8df920ae-2a09-42d3-8950-d2265d2e09b1)

**Comment by Adnan-shariff** [comment]
facing same issue : 
for SLU 
type of evaluation: GE
degree of evaluation : UG and PG

**Comment by shivanim11** [comment]
@pankajsparihar sent to next level from evaluation state getting error
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/fe0472ec-434d-43fd-a188-3a4d3e1c3bec)

**Comment by shivanim11** [comment]
Fixed
