### ISSUE TITLE
resolve warning in my teams

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#154]
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/108262338/b3306953-61e7-4d77-a751-807e66f7dfdc)

**Comment by sl-repo** [comment]
this is data issue corrected

**Comment by Adnan-shariff** [comment]
working as intended hence closing the issue 
![2024-06-12 12_39_03-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/40b1c244-5a4e-436c-89da-1c51ba67ff08)
![2024-06-12 12_38_39-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/b4004b41-63a3-4a97-99ea-7c00de25de95)
