### ISSUE TITLE
Admin Account: "sign out" shows an error "Access token has been revoked"

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#159]
**Describe the bug**
Clicking on "Sign out" displays an error message stating "Access token revoked."

**Scope of the bug**
Admin account > sign-out functionality.

**Steps to reproduce**
1.Log in.
2.Click on "Sign out."

**Expected Behavior**
Logging out should be successful without encountering any errors.

**Actual Behavior**
An error message pops up indicating "Access token revoked," preventing successful logout.

![2024-06-10 11_59_11-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/e618505e-aafb-441b-a4fe-7c31e4cfaf65)
![2024-06-10 11_58_43-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/68dbf444-8a25-4c67-a360-620d3555b03f)

**Comment by thirumeni-ram** [comment]
same Issue -
[not able to logout #143](https://github.com/Globalshala/Eval-Bridge-bugs/issues/143)

**Comment by shivanim11** [comment]
Fixed
