### ISSUE TITLE
Send to next level save call validations

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#16]
**Describe the bug**
Current behavior 
when there is no GPA and we clicked on send to next level then save call is there.  >>wrong behavior
When there is GPA and we clicked on send to next level then save call is there >> Correct behavior.

**To Reproduce**
1. Go to 'type of evaluation'
2. evaluate 1 app and there should be GPA/no GPA 
3. click on send to next level

**Expected behavior**
if GPA is not there then we need to restrict the save call.

**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/b2f699a6-d877-4046-8224-357e1d448c22)

**Comment by diyatalwarr** [comment]
PR raised: #287 Credential-Eval-Frontend

**Comment by mansi38299** [comment]
IF gpa value would be 0,0.00 ,null or undefined 
we should not allow user to proceed to next level

**Comment by shivanim11** [comment]
Fixed
