### ISSUE TITLE
Attributes coming blank in csv export

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#161]
When master upload is completed, the attributes such as Program duration, No of repeats are coming blank when the value is set 0.

steps 
1. Evaluate 1 application
2. set Program duration and no of repeats 0
3. do master upload
4. check csv export file

Drive - https://drive.google.com/file/d/1YoKWnYeKhfD3k5J4_BtxBAhshnDSGTzC/view?usp=sharing

**Comment by shivanim11** [comment]
@AnkitExcelerate

**Comment by AnkitExcelerate** [comment]
LGTM
