### ISSUE TITLE
total  cgpa number field in ge should be text field in cbc

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#163]
1. in cbc evaluation it should be text feild
2. previously we were not able to add text in total cgpa for CBC evaluatotion
expected: we should be able to add text input in total cgpa in CBC evaluations

**Comment by AnkitGS** [comment]
@NavnathGunjal7 Could you please review this pull request?

**Comment by shivanim11** [comment]
Not Fixed on dev

**Comment by AnkitExcelerate** [comment]
Working in dev
