### ISSUE TITLE
get name of evluator when hover on user code

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#166]
1. get name of evluator when hover on user code
2. in second page ther is user code if we hover on it show user first name last name  
3. to solve will need frontend backend changes from where we are fetch data in that api check if eval_by exists if exists fetch user data and add in eval_by_name attribute send to frontend on frontend on hover show that attribute
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/108262338/727bb084-06bd-45f3-bc28-b3b9236cbe5c)

**Comment by kartikatyagi** [comment]
Not working as expected it is not showing for single degree application Appid: App#slu9632448
and also for dual degree in account : App#slu265412 
kartika@globalshala.com 
Screen recording for both dual degree and single degree application:
https://www.loom.com/share/77445b4b5a7242b09409faa765cc7928?sid=14bddc35-b2b6-48af-8989-1fe2150f86ee
and also checked for another account shivani@vempower.org
in this account it is working for dual degree application Appid: App#slu32697 and not working for single degree application Appid: App#slu5697458
screen recording for both dual and singe degree application

**Comment by kartikatyagi** [comment]
fixed on dev working as expected

**Comment by kartikatyagi** [comment]
closing as working as expected
