### ISSUE TITLE
Apply leave onBhalf issue

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#17]
**Describe the bug**
when we apply leave on behalf of user we are getting error message and success message also. leave is not present in leave request.
**To Reproduce**
1. Go to 'Apply leave in team leader role'
2. Click on 'apply leave on behalf'
3. Apply leave 

**Expected behavior**
leave should apply without error
**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/8a3e7e6e-b09a-4ad5-a8aa-fc53b7f70e95)

**Comment by AnkitExcelerate** [comment]
Email of team leader is present in email column of leave request when the email of the user on whose behalf request is made should be there.

**Comment by shivanim11** [comment]
Fixed in dev
