### ISSUE TITLE
Application Lists: Appid not assigned to any user: Upload High Priority by CSv file or Priority filter button: we receive email but not present in my work 

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#170]
**Describe the bug**
When we try to upload an app from CSV file if the appid is not assigned to give priority it shows successfull message and also we receive email but it is not present in my work 
**Same issue in CSV file upload or by priority filter button**

**Scope of the bug**
Application lists >Apply priority by Uploading High Priority Applications by CSV file and also by Priority filter Button for **appid who has not been assigned to any user** 

**To Reproduce**
1.Click on Application lists
2.Click on Upload High priority applications
3.Upload a file with CSV file or priority filter button to apply priority for appid who doesnt have user assigned
4.We will receive email that it is assigned 
5.but in my work section of the user assigned app id is not present

**Expected behavior**
when we upload the appid, or apply priority from priority filter button , priority should be assigned and appid should be present in users account.
**applying priority from csv file and from priority filter button**
should assign priority and appid should be present in user account

**Actual Behavior**
We receive success email that priority has been assigned but if we check in My work section of the user appid is not present
for both cases from csv file or from priority applying button

![2024-06-12 17_44_44-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/b8f8b54c-bef1-4802-80a9-cec2a9e0ca7b)
![2024-06-12 17_45_07-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/1e02dd0b-d786-49bc-9dd5-e422726d8696)
![2024-06-12 17_46_46-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/90b759e1-7412-4353-a861-7926903fefaa)
![2024-06-12 17_47_37-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/bc479719-2dbe-4075-9403-880667a673d4)

**Comment by Adnan-shariff** [comment]
Not fixed yet please check the screenshots attached #128 
also it shows user has been assigned but doesnt.

**Comment by Adnan-shariff** [comment]
not fixed on dev yet.

**Comment by shivanim11** [comment]
Its assigned and showing in my work also
