### ISSUE TITLE
Getting success response when appid attribute is deleted from import map

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#171]
Deleted the appid attribute from the import map and not from the csv file to upload application, got success response from the system and the applications are not uploaded in the system.

Steps - 
1. Delete appid from import map
2. Dont delete the appid column  in csv file
3. Upload the csv file in drive and add in the system
4. Got success reponse.

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/6c115195-e1e7-467a-bec8-e10ee8d3033b)
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/c5c99b0f-434d-4faf-bd72-25cff00efcd7)

**Comment by AnkitExcelerate** [comment]
When deleted first_name and last_name getting an error that those attributes are required but not for appId

**Comment by MSGlobalShala** [comment]
> When deleted first_name and last_name getting an error that those attributes are required but not for appId

Have you checked entry in database? like what is SK of that application?

**Comment by AnkitExcelerate** [comment]
@MSGlobalShala Yes

**Comment by shivanim11** [comment]
@AnkitExcelerate please verify

**Comment by MSGlobalShala** [comment]
@AnkitExcelerate please verify on priority

**Comment by AnkitExcelerate** [comment]
working in dev
