### ISSUE TITLE
Redistribution error 

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#172]
When a user have capacity and want to redistribute applications but we are getting an error that **there are no users with capacity**. When tried with all the org code it works but when tried for a single organisation we are not able to redistribute the applications.

Steps- 
1. Put all users eval capacity to 0 expect for 1 user with only single org such as SLU
2. Redistribute application to that user
3. error

Expected result - Application for that single org should get redistributed
Actual Result -  Getting error that user don't have capacity

**Comment by shivanim11** [comment]
@AnkitExcelerate verify and close if resolved

**Comment by AnkitExcelerate** [comment]
Working in Dev
