### ISSUE TITLE
Application list: Filter Scroller Not Working When Scrolling Back

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#173]
**Describe the bug:** 
When users search for "1234" in the filter, they can scroll down to see the results, but the scroller becomes unresponsive when attempting to scroll back up.

**Steps to Reproduce:**

1. Select Illinois Institute of technology or any Organization
2. Enter "1234" in the search bar.
3.  Scroll down to see the results.
4. Attempt to scroll back up to the previous results.

**Expected Result:** 
The scroller should allow smooth navigation both down and up the results list.

**Actual Result:**
The scroller does not respond when attempting to scroll back up the results list.

![2024-06-13 14_16_22-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/e5cc8bd0-b493-4f19-be8f-85cae6f30329)

**Comment by NavnathGunjal7** [comment]
@Adnan-shariff as all results are loaded so there is no scroller it will be coming only when there will be 10+ results

**Comment by Adnan-shariff** [comment]
please check with different organizations its not scrolling back when we have more results.

**Comment by Adnan-shariff** [comment]
Hi Navnath Please check as its not fixed yet  we are not able to scroll to the previous results .
![2024-06-19 13_40_18-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/0215737b-e0f7-40d5-aaf0-e6ac2d7697d6)
![2024-06-19 13_40_10-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/3d39b9c9-dafd-459a-9ed6-b5e3a9a0bca5)
![2024-06-19 13_39_24-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/145bc866-f4a4-40cf-91bd-b95ae02f670e)
![2024-06-11 11_38_39-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/d2966363-24c1-486f-83fd-7cd4849a4bcb)

**Comment by Adnan-shariff** [comment]
working as intended.
![2024-06-21 16_41_26-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/1dd6088b-8f9f-4800-a892-bf3e2ace676d)
![2024-06-21 16_41_04-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/9c20e478-71da-42ec-8eca-bdfcd1c56cd4)
![2024-06-21 16_40_53-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/d3033f4a-e59a-4a93-a1ef-e5422eacc4a1)
