### ISSUE TITLE
Archive User Issues

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#180]
Issue 1 - 
When user is archived, the user id is coming in assign appid to specific user dropdown. Ideally when user is archived the it should not be available in that dropdown
Expected Result - Archived user should not be available in the user dropdown

Issue 2 - 
When user is archived, application assigned to that user should get redistributed.
Expected Result - Application should get redistributed when user is archived

**Comment by AnkitExcelerate** [comment]
when i undo the archive the priority of applications is not in proper format and some applications got redistributed
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/64c8fba0-d3cd-47f4-83dd-ec93783c856f)

**Comment by Adnan-shariff** [comment]
working as intended as issue 1 and issue 2  is working as expected.
