### ISSUE TITLE
My Work Issues 

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#181]
Issue 1 -
Search functionality only works for the current page and not for the others

Issue 2-
The Priority added to application is not in proper manner, the application should get arranged with respect to Date of assignment and priority i.e recently prioritized application should come at bottom and older ones at top

**Comment by kartikatyagi** [comment]
Issue 1 : Fixed on dev working as expected 
![image](https://github.com/user-attachments/assets/c99e8007-3f1b-4a35-af23-38bd8449baa3)
![image](https://github.com/user-attachments/assets/aa7450cd-c949-4147-88ad-b171b0de2726)

Issue 2:  working as expected 
set priority low :
![image](https://github.com/user-attachments/assets/ec82ab70-08a6-4a47-a070-3aa46627cc06)

recently prioritized apps showing at bottom:
![image](https://github.com/user-attachments/assets/09404126-6da6-4f40-85fe-8017e26d2231)
