### ISSUE TITLE
Organisation Code should be editable when we click on edit icon

### ISSUE THREAD

**Issue by mansi38299** [Globalshala/Eval-Bridge-bugs#182]
<img width="1440" alt="image" src="https://github.com/Globalshala/Eval-Bridge-bugs/assets/79189076/e3d9c63e-9358-42a0-97f6-60d99fec4e21">

We need to Org code for every user in the form of chip,
on clicking of pencil icon it will be editable.
when user edit that ,or remove something
on Clicking of save icon we need to save org code and capacities

**Comment by shivanim11** [comment]
Not fixed
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/deb0ca4a-05f1-4766-ae5f-c30d3c94c909)

**Comment by shivanim11** [comment]
Fixed AND updating in DB also
