### ISSUE TITLE
Not changing value of total US credits based on ug equivalency

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#184]
**Describe the bug**
select two year undergraduate equivalency click on cbc and again back to TOF page and change the equivalency. so on cbc total required credit should change accordingly.
updated equivalency passing from payload also 

**Expected behavior**
it should change based on the equivalency.
**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/df2e90ed-d477-4b95-bb32-6f68d918a96a)

**Comment by pankajsparihar** [comment]
works as intended , first we need to clear the cbc data because it gives preference to saved data. When there is no data in cbc fthen irst time it will change the us equivalency  as we change the us equivalency and save it in DB .
