### ISSUE TITLE
Master upload- data is blank in report

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#185]
**Describe the bug**
in csv file report is blank not getting proper data

**Expected behavior**
it should contain all mentioned data
**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/4bc40eed-b4b4-4093-9dcb-62233108541c)

**Comment by MSGlobalShala** [comment]
https://drive.google.com/file/d/11bPWiuN0e_BUAtzm1q7Hxdn0WQkki1MX/view

**Comment by shivanim11** [comment]
Fixed in dev
