### ISSUE TITLE
total US credit not changing with US degree equivalency

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#187]
When total US credit in cbc page is edited once and then US degree valency is changed then the total US credits is not changing in cbc page

**Comment by pankajsparihar** [comment]
works as intended , first we need to clear the cbc data because it gives preference to saved data. When there is no data in cbc fthen irst time it will change the us equivalency  as we change the us equivalency and save it in DB .

**Comment by MSGlobalShala** [comment]
@AnkitExcelerate can you please check this

**Comment by AnkitExcelerate** [comment]
Working as expected
