### ISSUE TITLE
send back to evaluator - shows error "Invalid UpdateExpression: Two document paths overlap with each other: must remove or rewrite one of these paths; path one: [is_archived], path two: [remarks]"

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#193]
**Describe the bug**
when we click on Send back to evaluator its showing an error message 

**Steps to reproduce** 
Evaluation Level - Global Graduate Courses

Degree of Evaluation - Undergraduate

Type of Evaluation - General Evaluation

Ug country - India
 
Ug Scale -  10  CGPA 
 
**Expected Behavior**
The functionality to return the appid to evaluator without any error 

**Screenshots**
![2024-06-20 18_13_57-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/531d577f-0e30-4fc9-af6c-a23cd8abbb37)
![2024-06-20 18_13_35-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/c5bc14b8-84be-4747-beb6-9534a43435ee)
![2024-06-20 18_04_49-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/4e88dc9b-4ad2-41a3-9148-bdbf2b5a0785)
![2024-06-20 18_04_42-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/f4eedc1e-fc59-46e3-948c-2c4f42d673a4)

**Comment by Adnan-shariff** [comment]
issue not reproducible .

**Comment by kartikatyagi** [comment]
It is working as expected the app id is successfully send back to the evaluator: 
Screenshot: 
![image](https://github.com/user-attachments/assets/506bde88-034c-4b0f-af29-3e17cb19e1b1)

![image](https://github.com/user-attachments/assets/3a9606d7-17fb-45ab-84dc-01c451cbd4b7)
