### ISSUE TITLE
getting issue on CBC page for first row

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#194]
**Describe the bug**
first row not accepting decimal values and not less than 9 if scale is 20, if scale is 10 then its not accepting less than 5

**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/7d5e6144-005b-44c1-9913-e1302bec3bc3)

**Comment by AnkitExcelerate** [comment]
Working in dev
