### ISSUE TITLE
Grade scale Archive: Email Notification: The email notification is showing as " undefined" for the username in the email body.

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#196]
**Describe the bug**
The email notification is showing an undefined value for the username in the email body after approving grade scale archive request

**Scope of the bug**
Grade scale archive : Approved email notification

**Expected Behavior**
The email body should display the username of the recipient when approved for archiving grade scale .

**Actual Behavior**
The email body displays as " undefined" user for the username 

**Screenshots**
![2024-06-21 01_36_55-Edit item _ Amazon DynamoDB Management Console _ DynamoDB _ ap-south-1](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/70ceb9e1-eca6-47de-8f61-46ec989680d2)
![2024-06-21 01_36_23-Your request for archiving grade scales is Accepted - adnan@vempower org - Excel](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/6388cf1e-ba62-4a76-9680-89165d59fc48)

Issue 2:

Notification email for edit grade scale new edit request raised does not contain Username in email body.

![2024-06-21 11_52_25-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/c8910732-a184-471d-8349-42c927954d5a)

**Comment by Adnan-shariff** [comment]
working as intended on dev , hence closing this issue 
![2024-06-21 16_40_53-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/ae9c0f5e-c288-43b7-9668-944d27b8d4f5)
![2024-06-21 16_41_26-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/b0ea08cd-bf1b-4cf2-9998-49aa3c758c15)
![2024-06-21 16_41_04-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/652146d3-47cb-47c7-90b6-6e89a424f624)

**Comment by shivanim11** [comment]
Fixed
