### ISSUE TITLE
Degree of Evaluation Dropdown 

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#197]
In type of evaluation page, the degree of evaluation dropdown consist options such as **Under Graduate & Post Graduate** but when selected those options then we get **Undergraduate & Postgraduate** in those fields

Expected Behavior - The dropdown option and selected option should be same in that text field

Screenshots - 
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/eda46aa2-4744-49a9-ae12-39479a668a93)

**Comment by shivanim11** [comment]
Fixed on Dev
