### ISSUE TITLE
CGPA Textfield Update Bug

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#198]
**Describe the bug:**
When attempting to change the total CGPA and clicking on save, the textfield retains the previous CGPA value instead of updating to the new one.

**Scope of the bug:** 
CGPA textfield
 
**Steps to reproduce:**
1. Enter `2` in the total CGPA textfield.
2. Click on the "Save" button.
3. Edit the total CGPA textfield to `3`.
4. Click on the "Save" button again.
5. Observe the value in the total CGPA textfield.

**Expected Behavior:** 
The textfield should display the newly entered CGPA value after clicking "Save."

**Actual Behavior:** 
The textfield retains and displays the previously entered CGPA value instead of updating to the new one.

**Screenshots:**

**Comment by shivanim11** [comment]
updating total CGPA
Fixed
