### ISSUE TITLE
My profile:  Organization Name display is missing  

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#199]
**Describe the bug:**
 The organization name is not displayed in the user profile, 

**Scope of the bug:** 
My Profile

**Expected Behavior:**
The user profile should display the organizations linked with that user.

**Actual Behavior:**
The organization name is missing from the user profile display.
![2024-06-25 10_37_52-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/e32af580-55ef-4bd3-84f1-92aeb5a232ea)

**Comment by Adnan-shariff** [comment]
![Uploading 2024-06-25 11_29_18-Window.jpg…]()

**Comment by Adnan-shariff** [comment]
![2024-07-09 10_36_59-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/c33610dd-e222-4335-ad17-3b0c8a73d23c)

**Comment by shivanim11** [comment]
Fixed on dev
