### ISSUE TITLE
Search functionality in My work

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#2]
Search functionality in my work only works for 1st page 

1. create a backend API to search the application in my work section instead of searching on frontend

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/fe27f9b1-8e83-47cc-abcd-89a97885a74c)

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/e04be2c4-9cba-432f-b6b1-99cca0858f1d)

**Comment by shivanim11** [comment]
Fixed on dev
