### ISSUE TITLE
Table content not visible when added csv file in assign appid to specific user

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#20]
In assign appid to specific user, when uploaded the csv file the table is empty and the csv file contents are not visible in the table.
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/37eaa0ed-ed50-4f0f-b541-4f4c192d077f)

Expected Result - When csv file added, the contents should be visible in the table.

**Comment by shivanim11** [comment]
Fixed on dev
