### ISSUE TITLE
CBC: Fetch prev data issues: it will not fetch prev data of PG details and also it will not fetch CBC data at 2nd time of UG 

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#200]
**Describe the bug:** 
Issues: 
**1.Data is not fetched in the PG section, whether within the same organization or across different organizations**
**2.when we try to fetch ug data for second time in a new app we are not able to fetch**
CBC Data should be fetched if university and major matches in the apps we enter the  same university and major .

**Scope of the bug:** 
**CBC : PG - fetch prev data 
CBC: UG DATA: fetch prev data:  when we try to fetch for second time in a new app we are not able to fetch** 

**Expected Behavior:** 
The PG data should be fetched and displayed correctly both within the same organization and across different organizations.

**Actual Behavior:** 
The PG data is not fetched or displayed correctly either within the same organization or across different organizations.

please reach out to me to reproduce the issue .
**Screenshots:**  
![2024-06-25 16_15_46-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/a009b3e4-bdca-419d-bb46-e32bfc12e61e)
![2024-06-25 16_02_04-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/eb1cbc6f-58c4-40bd-971f-abe490512631)
![2024-06-25 15_57_44-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/ba96b916-a526-4527-9ecd-b36e346cf547)
![2024-06-25 15_56_18-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/85a3cebd-1839-4a53-9695-5bb36926dcc5)

**Comment by NavnathGunjal7** [comment]
@AnkitExcelerate  please verify and add your comments

**Comment by Adnan-shariff** [comment]
Working as intended .
we are able to fetch data for both UG and PG.
Hence closing this issue.
![2024-07-31 18_44_46-](https://github.com/user-attachments/assets/4411ea4c-f5bd-4369-8a3d-de67304b8381)
![PG1](https://github.com/user-attachments/assets/a2680e98-3d0a-4470-a9d5-a18c3bb4e4ba)
![ug3](https://github.com/user-attachments/assets/9a9b5f77-8662-4dbb-a727-ee529cca508c)
![2024-07-31 18_33_35-](https://github.com/user-attachments/assets/b77c0060-cba2-45bf-bc59-46524b96a1b2)
![ug](https://github.com/user-attachments/assets/d4cc4c76-f367-4477-89a2-9c0eadb19fbf)
![2024-07-31 18_47_30-Cred Eval Bridge](https://github.com/user-attachments/assets/0718c8bf-9fee-4f21-bd75-aed55e85dd2c)
