### ISSUE TITLE
Text field value changes on scroll

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#202]
**Describe the bug**
When interacting with a text field, using the scroll wheel or touchpad changes the value within the text field. This behavior is unintended as the text field should only accept string and numeric inputs, and should not change its value when the screen is scrolled.

**Scope of the bug**
Type of evaluation: 
**Total CGPA 
Number of repeats
Duration Of Program** 

**Expected Behavior**
The text field should only accept string and numeric inputs. Scrolling the screen or using the mouse scroll wheel should not affect the value in the text field.

**Actual Behavior**
When the text field is focused, scrolling changes the value within the text field.

**Screenshots**

**Comment by Adnan-shariff** [comment]
![2024-06-26 19_32_16-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/70c8b9ea-72d7-4c45-8bc1-0879f3c00174)

**Comment by Adnan-shariff** [comment]
https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/8b7a5610-b79c-4771-b9d7-dfd328372780

**Comment by kartikatyagi** [comment]
Working as expected Fixed on dev 
Screen recording attached :

https://www.loom.com/share/04dcf5f7036e4a2080eb7e1e6d90873f?sid=db4f954a-1674-485f-a4cc-105937cb53df

**Comment by Adnan-shariff** [comment]
Issue is not fixed hence re-opening the issue .

**Comment by kartikatyagi** [comment]
working as expected 
screen recording attached:
https://www.loom.com/share/5dfbc186bb754b51bc1f4a749c27b31d?sid=22741e13-3bea-4d77-930c-3ecd3e882edb

**Comment by Adnan-shariff** [comment]
working as expected.
