### ISSUE TITLE
My profile: Capacity Doesn't Update on My Profile as It’s Updated in My Team Review Capacity or Evaluate Capacity

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#204]
**Describe the bug**
When updating capacity in the Team Review Capacity or Evaluate Capacity sections, the changes are not reflected in the My profile page.

**Expected Behavior**
The capacity displayed on the My profile should match the updated capacity as seen in the Team Review Capacity or Evaluate Capacity sections.

**Actual Behavior**

The capacity displayed on the individual My profile does not reflect the updates made in the Team Review Capacity or Evaluate Capacity sections.

**Screenshots**
![2024-07-03 13_37_18-Media Player](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/aa71c2a1-72a4-46ca-8f82-5c42d9343d02)
![2024-07-03 13_36_59-Media Player](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/83d416d2-a79c-4d32-a132-eef6cac89b8b)
![2024-07-03 13_35_01-Media Player](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/f79b7e24-02fd-4951-a4ba-a1bd4bbbaa7e)
![2024-07-03 13_34_27-Media Player](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/b95d65e1-aaab-434b-9957-c7a6093ef9db)
![2024-07-03 13_33_05-Media Player](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/5f618dd0-10b5-4d8f-9e4b-df8d8a987513)

**Comment by pankajsparihar** [comment]
Working fine checked dev. just need to refresh the page after changing the capacity.

**Comment by Adnan-shariff** [comment]
working as intended we need to refresh after we update the capacity and it will be updated.
