### ISSUE TITLE
Application status is not correct in application list

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#205]
Evaluate one application and send it to next level for review and from there send it back to evaluator. Check the status of application in Application list, the status is review_inProgress when the application is in evaluation.

Steps - 
1. Evaluate 1 application
2. Send it for review
3. send back to evaluator
4. check status of application in application list

Screenshot - 
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/28912f76-c880-497e-9b2c-aa65d5098f14)

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/c1117c90-01f0-4977-9d28-beafded8821d)

**Comment by kartikatyagi** [comment]
Fixed on dev working as indented
![image](https://github.com/user-attachments/assets/6b3c7067-3561-4582-9302-aabfd8434332)
