### ISSUE TITLE
Send back to evaluator

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#206]
When application is evaluated and reviewed by same user and from review it is send back to evaluator, application is getting assigned to some other user.

Steps - 
1. Evaluate 1 application and review it from same user
2. send back to evaluator 
3. check assigned user

Expected behavior -  The application should get assigned to evaluator who evaluated that application

**Comment by shivanim11** [comment]
Fixed
