### ISSUE TITLE
Leave on behalf from team lead account

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#209]
When we apply leave on behalf from team lead account we are able to apply leave for same date multiple times for the same user

Steps - 
1. Apply leave on behalf of user1 for 13/7/2024
2. do the step 1 again
3. Check leave request
4. there are 2 request for the same date and user

Screenshot - 
![image](https://github.com/user-attachments/assets/66d2f0a7-6235-4f7e-ba42-8786b93c5466)
![image](https://github.com/user-attachments/assets/27889a66-b0b9-48d1-8ba1-5fd50c6987a8)

**Comment by kartikatyagi** [comment]
Tried to apply leave on behalf from team lead account followed the same 
Steps and we can apply for multiple leaves for the same date 12/07/24 for same user 
**It is not giving any error message**
screenshot attached :
![image](https://github.com/user-attachments/assets/40e366bb-fd5a-4e9e-a0fb-36db42d64df0)

**Comment by kartikatyagi** [comment]
Working as expected 
We cannot apply leave for same date again from team lead account for User , it is throwing the error message 
**Screenshot attached :** 
![image](https://github.com/user-attachments/assets/2149e6d6-6071-4385-b65f-84d92ca9f51b)
![image](https://github.com/user-attachments/assets/6dcf027b-5152-48ea-9355-4bb881e429e2)
