### ISSUE TITLE
Send back to evaluator button is not there when we are doing dual degree evaluation

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#210]
When we are doing dual degree evaluation, send back to evaluator is not there in review.

steps - 
1. evaluate 1 application for dual degree
2. send to next level
3. in review check send back to evaluator button

Test Data - dpu856597 
User - Navnath@vempower.org for review

Screenshot - 
![image](https://github.com/user-attachments/assets/253d0e8c-6016-4347-80e4-463fea94df33)
![image](https://github.com/user-attachments/assets/11379028-91d3-4697-958d-047fa9c9da20)

**Comment by AnkitExcelerate** [comment]
not getting remarks when application send back to evaluator
![image](https://github.com/user-attachments/assets/cfb5028f-ed4c-416d-80e2-1d5226f1651c)
![image](https://github.com/user-attachments/assets/c01aa63c-6b27-4aa5-9daa-aebba446d169)

**Comment by shivanim11** [comment]
Able to send back to eval but Remark is not there 
![image](https://github.com/user-attachments/assets/6ec770a4-f531-40b7-925b-2b160fd44cd1)

**Comment by kartikatyagi** [comment]
working as expected : 
screenshot: 
![image](https://github.com/user-attachments/assets/011785da-0b55-4df3-8ad0-feeed78b7f4f)
![image](https://github.com/user-attachments/assets/dece05e1-c011-49f5-9d83-534c70e904bf)
![image](https://github.com/user-attachments/assets/edf4e668-b061-437c-ab06-ebd19b68b2a9)
