### ISSUE TITLE
Status is inaccurate in application list

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#213]
When evaluated one application and assigned it to bunch of user for evaluation and then send it to next level, send that application back to evaluator and check status in application list. 

Steps- 
1. Evaluate 1 application and assign to 2-3 user for evaluation only
2. Send to next level
3. Send back to evaluator
4. Check status of application in Application list

Test Data - **App#**slu65465****

Expected behavior -  Application status should **eval in progress** in application list

Screenshot - 
![Screenshot from 2024-07-17 13-26-01](https://github.com/user-attachments/assets/773d4d9c-752f-48cf-902f-0d53db423212)
![Screenshot from 2024-07-17 13-27-00](https://github.com/user-attachments/assets/9f6abf8c-d071-4d74-b1de-93d9fa444ab2)
![Screenshot from 2024-07-17 13-46-31](https://github.com/user-attachments/assets/418e7391-f5e0-437b-a035-fa426639bbcb)

**Comment by MSGlobalShala** [comment]
Duplicate with #205
