### ISSUE TITLE
If user is on leave, not able to assign application forcefully 

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#214]
When user is on leave then not able to assign application to that user via Assign appid to specific user. Getting an pop up error in which it says "Cannot assign appid to user on leave"

Steps- 
1. User should be on leave for the day
2. assign appid to specific user 
3. get pop up error

Expected Result - We should be able to assign application to that user

![Screenshot from 2024-07-15 20-39-41](https://github.com/user-attachments/assets/93178e41-0e3b-4f14-b2dd-dbd0ce2e02e8)

**Comment by AnkitExcelerate** [comment]
Fixed in PR ISSUE-210

**Comment by shivanim11** [comment]
Fixed,
working as expected
