### ISSUE TITLE
My teams dropdown issue

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#215]
When selected name in dropdown and searched it in the textfield we are getting the name but when changed dropdown option from name to email there is no api call to load the data.

Steps - 
1. Select name in dropdown 
2. add name in text field
3. change dropdown from name to email
4. no changes in UI

screenshot - Changed name to email in filter by and there was no api call was made or atleast it should clear the field when dropdown option is changed

![image](https://github.com/user-attachments/assets/4cad89cb-1ccf-466d-a4ec-0932500ba4e8)
![image](https://github.com/user-attachments/assets/80b61031-0a80-48f3-914f-16b248e24dd5)

Expected result - when dropdown is changed then the text field should be cleared.

**Comment by kartikatyagi** [comment]
working as expected: 
when we select the filter and search the email id :
![image](https://github.com/user-attachments/assets/142e9e2c-466e-46d5-930f-938842d93fc4)
changing the firter to name : 
![image](https://github.com/user-attachments/assets/36c0b64c-d302-41c6-a3e5-a422b1d076ed)
changed the filter to name: 
![image](https://github.com/user-attachments/assets/6d603374-8292-41ae-bfec-6e1ca5b9db94)
