### ISSUE TITLE
Leave requests are not sorted in  My Leave section

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#216]
In My leave section the leave request are not sorted in any manner, the recently made request should be on top of that request section.

Screenshot -
![Screenshot from 2024-07-19 12-55-15](https://github.com/user-attachments/assets/a26a187d-604e-4b93-bf96-33e97b124abd)

**Comment by kartikatyagi** [comment]
working as expected:
screenshot:
![image](https://github.com/user-attachments/assets/dcc1e354-0198-4b4c-a32f-72beaa466606)

**Comment by kartikatyagi** [comment]
Not working as expected the order for accepted and rejected leave is sorted 
![image](https://github.com/user-attachments/assets/e260d86e-3af0-4d16-b53f-8c9d03fc5489)

**Comment by MSGlobalShala** [comment]
@shivanim11 please assign someone for testing

**Comment by kartikatyagi** [comment]
Working as expected the recent raised request is coming at the top and the order accepted and rejected request is sorted.

**Screenshots:** 

![image](https://github.com/user-attachments/assets/95fc747e-4105-4901-b8c4-e093fa1976e9)

![image](https://github.com/user-attachments/assets/590d3788-06f9-40e7-858e-9dea11f3d04f)

![image](https://github.com/user-attachments/assets/7ecb9368-5c02-4b54-a7ba-a41734b79214)



![image](https://github.com/user-attachments/assets/d021d42e-6e20-4d83-99fa-1e7a06e1cae4)
