### ISSUE TITLE
Email Template issue

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#220]
**Describe the bug**
1. blank keyword is getting in high priority application and daily app status
2. username is not coming in archive grade scale, grade scale edit
3. send back to eval is not used its using high prio application list template
**To Reproduce**
4. Click on '....'
5. Scroll down to '....'
6. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kartikatyagi** [comment]
working as expected 
![image](https://github.com/user-attachments/assets/5e95dc2a-aff9-4031-8644-5abd468dba08)
![image](https://github.com/user-attachments/assets/6b2bb14e-b106-412c-94c1-73748d855da8)
![image](https://github.com/user-attachments/assets/53a2b374-9727-4da9-a3f4-df04c0ed8a76)
