### ISSUE TITLE
Transcript display size should be fullscreen

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#221]
Issue 1 - Transcript in cbc page should get displayed in full page.
![image](https://github.com/user-attachments/assets/88031330-fedc-465d-84c8-e6b6bd9ee9f3)

Issue 2 - Transcript in highschool should display full page.
![image](https://github.com/user-attachments/assets/6ead17ec-e7e0-4fcc-bc9e-9e791d38735e)

Issue 3 - In Mobile view we are not able to see transcript in evaluation pages
![image](https://github.com/user-attachments/assets/066d93b8-c150-4593-b288-4a33f2087b04)

**Comment by kartikatyagi** [comment]
Working as expected 
screenshots: 
![image](https://github.com/user-attachments/assets/8a51883a-0327-4884-8c89-202903e7500c)

![image](https://github.com/user-attachments/assets/28b5f930-113d-46cd-af38-12f76eeecb9a)

![image](https://github.com/user-attachments/assets/11faa011-8ff5-4091-b99c-b9e22cbb0344)
