### ISSUE TITLE
Application list: Search by app id Search box  should accept  alphanumeric characters.

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#222]
**Describe the bug**
The search box in the application list does not accept alphanumeric characters.
It currently only allows numeric input.

**Scope of the bug**
This bug affects the search functionality for applications with alphanumeric identifiers,
preventing users from finding such applications.

**Steps to reproduce**
1. Open the application.
2. Navigate to the application list.
3. Attempt to enter an alphanumeric  Appid(e.g., "slu123") in the search box.

**Expected Behavior**
The search box should allow and accept alphanumeric characters so that users can input full appid

**Actual Behavior**
The search box only accepts numeric input and ignores or rejects any alphabetic characters.

Screenshots
![2024-07-26 17_32_29-](https://github.com/user-attachments/assets/c6fd109d-f33c-4be6-bdc1-8aedd82e41fd)

**Comment by pankajsparihar** [comment]
input should be numeric value only

**Comment by MSGlobalShala** [comment]
Converted to dropdown now
