### ISSUE TITLE
Import: Error Message should be displayed when Max appid length size is less than Min appid size

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#223]
**Describe the bug**
When force: true is set with an appid size where the maximum size is less than the minimum size, file import is successful.

**Scope of the bug**
Import
Db: Force true
Max appid < Min appid size

Steps to reproduce
Set the appid size minimum size to 10.
Set the appid size maximum size to 6.
Attempt to upload a file of appid size 3.
The file is uploaded with leading zeros.

**Expected Behavior**
The upload should fail, and an error message should indicate that the file size does not meet the required constraints.

**Actual Behavior**
The file is uploaded successfully.
![2024-07-29 18_06_34-20240728 - Microsoft Excel](https://github.com/user-attachments/assets/48e997cd-cc55-4544-b0ee-9d23dcb975e9)
![2024-07-29 18_05_56-20240728 - Microsoft Excel](https://github.com/user-attachments/assets/4e9a98ce-e5d7-4b08-a2fb-39f5ad171867)
![2024-07-29 18_08_57-Settings](https://github.com/user-attachments/assets/c976bebe-5313-4d17-9271-5714598715bc)
![2024-07-29 18_08_19-Settings](https://github.com/user-attachments/assets/c559e68f-6796-4b4c-aea3-4ef62b49db54)
![2024-07-29 18_07_47-Window](https://github.com/user-attachments/assets/27570abb-0cd2-45a0-b6a0-83ac72c3d5a4)
![2024-07-29 18_06_47-20240728 - Microsoft Excel](https://github.com/user-attachments/assets/b905bb9b-bfc2-4855-a19c-d278e1caaae2)

**Comment by shivanim11** [comment]
@Adnan-shariff Please verify this asap

**Comment by Adnan-shariff** [comment]
working as intended please check the screenshot attached.
![2024-08-02 17_17_23-Window](https://github.com/user-attachments/assets/cddabc2a-19e0-44db-b80f-89bc8dc940cb)
![2024-08-02 17_16_30-Window](https://github.com/user-attachments/assets/8b77a19f-6da1-4ba9-a48a-d2089238cc19)
![2024-08-02 17_14_56-Window](https://github.com/user-attachments/assets/32e2e652-74c7-46f7-9bfe-e5426a104203)
