### ISSUE TITLE
Autosave on/off issue

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#224]
**Describe the bug**
1. at time of evaluation if autosave is off and send that application to next level so at review stage autosave should be off. but currently its not happening
**To Reproduce**
1. Go to 'application turn off autosave button'
2. Click on 'send to next  level'
3. open appid from reviewer 

**Expected behavior**
autosave should be off

**Comment by MSGlobalShala** [comment]
Invalid bug
