### ISSUE TITLE
remark is not there for send back to eval

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#225]
**Describe the bug**
1. application is send back to evaluator with remark but that remark is not showing on UI.

**Expected behavior**
remark should be there
**Screenshots**
![image](https://github.com/user-attachments/assets/10a390ec-fabf-4650-b4ff-dc9c28340c78)
![image](https://github.com/user-attachments/assets/f45a9c41-426d-4682-b55d-62d2851eb7f8)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MSGlobalShala** [comment]
Previously there was one scenario also exist where "remark" was not visible in case of "Send back to evaluator".
Duplicate #228
