### ISSUE TITLE
If no file is on drive for import then throwing invalid error

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#227]
**Describe the bug**
if no file is on drive for import its showing invalid error please check attached screenshot

**Expected behavior**
it should show clear and valid message  to user
**Screenshots**
![image](https://github.com/user-attachments/assets/4aca6645-abee-4ab9-b3dc-2b1874ef6264)

**Comment by kartikatyagi** [comment]
Not working as expected 
 Screenshot attached : 
 
![image](https://github.com/user-attachments/assets/34b4d7fc-3b10-4c5b-87a0-fcf5250e4ea0)

**Comment by kartikatyagi** [comment]
Working as expected 
screenshot: 
![image](https://github.com/user-attachments/assets/e03f9973-5140-4f01-a7d2-f7637237b25b)
