### ISSUE TITLE
Down;load sample overlapping on Dropdown of org in assign appid to specific

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#230]
**Describe the bug**
Down;load sample overlapping on Dropdown of org in assign appid to specific

**Screenshots**
![image](https://github.com/user-attachments/assets/4c9aa039-6d19-42d2-9eb0-b467ead8f703)

**Comment by kartikatyagi** [comment]
Working as expected
screenshot attached : 
![image](https://github.com/user-attachments/assets/099ed703-3264-42f4-b296-27420c9c0ec0)
