### ISSUE TITLE
Redistribution: Issue in Equal Distribution for Two Users

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#231]
**Describe the bug**
When two users (User A and User B) are present and apps are distributed from User C, only half of the Appids  are assigned to User A, and the remaining Appids  are not assigned to any user.

**Scope of the bug**
Distribution of Appids between users.

**Steps to reproduce:**
1. Ensure User A and User B Have capacity
2. Distribute Appids from User C 

**Expected Behavior:**
Appids should be distributed evenly between User A and User B from User C according to their capacities.

**Actual Behavior:**
Only half of the Appids are assigned to User A, and the remaining Appids are not assigned from User C.

**Comment by MSGlobalShala** [comment]
Currently this bug is not a blocker for us. @NavnathGunjal7 will take this with organisation based capacity user story.

**Comment by kartikatyagi** [comment]
Working as expected
