### ISSUE TITLE
issue in letter grade For PG

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#232]
**Describe the bug**
this error getting when In UG its letter grade selected and for PG also letter grade
 
 
![image](https://github.com/user-attachments/assets/eecfdd3e-8344-455e-a38d-8c5c44b3b47d)

this error getting when UG have number grade and PG having letter 
 
![image](https://github.com/user-attachments/assets/f275d25a-1a5c-48b4-a2a8-26a941336c2a)

**Comment by kartikatyagi** [comment]
Working as expected , fixed on dev 
Screenshots: 
**For UG :** 
![image](https://github.com/user-attachments/assets/1a84b093-96a2-456b-b06b-235e96104495)

**For PG:** 
![image](https://github.com/user-attachments/assets/82b70db0-95d8-487d-a79a-d1e360720289)

**Comment by kartikatyagi** [comment]
working as expected 
screenshots : 
when for UG its letter grade selected and for PG also its letter grade:
![image](https://github.com/user-attachments/assets/1e07b40b-c42d-43d4-8e15-012a6a3d661b)
when UG it is number and PG it  is letter grade : 
![image](https://github.com/user-attachments/assets/2109eb1f-481c-4e75-98d3-7615d114e44e)
