### ISSUE TITLE
show the status also in email body

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#233]
**Describe the bug**
embed status in email body for application
EmailTemplate#ApplicationCurrentStateNotification
body:

You have been assigned the application.
Application ID :
Priority:
Status:

**Comment by kartikatyagi** [comment]
working as expected 
screenshot: 
![image](https://github.com/user-attachments/assets/09a188a6-de5a-47e9-90d8-b5980b2de5bb)
