### ISSUE TITLE
Grade scales: No Response When Accepting or Rejecting New Grade Scales

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#234]
**Describe the bug:**
When attempting to upload or reject new grade scales, the application does not provide any response or feedback, leaving the user uncertain if the action was successful.

**Scope of the bug:**
Grade Scales > My Task Approver >Add grade scales
**Steps to reproduce:**

1. Navigate to the Grade Scales section.
2. Upload Grade scales 
3. Goto my task approver 
4. Click on Add grade scales 
5. Accept or reject there is no response and 
6. if accepted to add also verified in DB its not added 

**Expected Behavior:**
The system should provide feedback indicating whether the grade scale was successfully uploaded or rejected.

**Actual Behavior:**
No response or feedback or any pop up is visible when attempting to upload or reject new grade scales.

**Comment by NavnathGunjal7** [comment]
@Adnan-shariff  please add screen shot of api or scale if i will able to reproduce it then only able to solve it

**Comment by MSGlobalShala** [comment]
@Adnan-shariff Is it a bug?

**Comment by Adnan-shariff** [comment]
Hi Manish this issue is not reproducible hence closing this issue.
