### ISSUE TITLE
Grade Scale Edit: Unexpected Issues

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#235]
**Describe the bug**
Page goes blank and also shows error message 

**To Reproduce**
1.Click on My Task Approver 
2.Click on Grade Scale Edit 
3.Click on First Req and Scroll 

**Expected behavior**
Page should load 

**Actual behavior**
Page Goes Blank and also shows error message 

**Screenshots**

![2024-08-02 12_44_40-Window](https://github.com/user-attachments/assets/544b0621-1ca4-4340-9672-8d8275ac8bae)
![2024-08-02 12_44_33-Window](https://github.com/user-attachments/assets/6ebf4ef9-53bd-4bf9-a74f-f29a96678660)
![2024-08-02 12_44_21-Window](https://github.com/user-attachments/assets/1ac51926-3311-4189-b553-4a88ea1c15a9)
![2024-08-02 12_44_04-Window](https://github.com/user-attachments/assets/e09f1bc4-f658-495c-9040-14beffc34f7f)
![2024-08-02 12_43_52-Window](https://github.com/user-attachments/assets/34a22be4-eb99-410f-af84-9879b70aa689)
![2024-08-02 12_42_31-](https://github.com/user-attachments/assets/108b6c96-1576-4004-9c3d-59b6c314c5f2)
![2024-08-02 12_42_22-Window](https://github.com/user-attachments/assets/9e9bf71b-d28b-4373-96d3-6b4e9d6a86da)
![2024-08-02 12_42_10-Window](https://github.com/user-attachments/assets/3c69d6f6-bc43-40a4-a6ba-f13e9427df84)
![2024-08-02 12_47_56-Window](https://github.com/user-attachments/assets/33e70cdd-1b68-4cbd-a36a-5e888ecc1144)

**Comment by Adnan-shariff** [comment]
![2024-08-02 12_53_55-Window](https://github.com/user-attachments/assets/91ffd61a-10dc-4ef1-a480-82a467ae9179)

**Comment by Adnan-shariff** [comment]
Issue 2: 

Archive grade scale req are not visible in my task approver few archive requests are not showing up in my task approver . we are getting email 
![2024-08-02 13_17_46-Window](https://github.com/user-attachments/assets/6c3faca3-2d1b-46c8-b795-974f66b9d48c)

**Comment by Adnan-shariff** [comment]
Issue 3: 
we are able to upload grade scale type with duplicates values in it **CGPA Scale 9 (1,2,3,4,5,6,7,9,9)**
![2024-08-02 14_23_55-Window](https://github.com/user-attachments/assets/3775bec9-fa39-4dde-9f0f-0624e770a1b5)

**Comment by Adnan-shariff** [comment]
issue 4: 

Add grade scale shows **44** requests or scales to be added but only 11 requests are only present in the page also we are not consistently receiving add grade scale requests 
![2024-08-02 14_41_31-2024-08-02 14_38_05-Window](https://github.com/user-attachments/assets/c07c5639-d0a1-436c-bcf9-b1418dee7776)
![2024-08-02 14_41_03-2024-08-02 14_38_13-Window](https://github.com/user-attachments/assets/3606557c-ab77-4b00-8f24-73bdf24c00ad)
![2024-08-02 14_40_29-2024-08-02 14_38_36-Window](https://github.com/user-attachments/assets/0b0890e1-9aa2-43f5-bd8e-2dde3140a0af)
![2024-08-02 14_38_05-Window](https://github.com/user-attachments/assets/eb8b6b99-92b5-4278-8548-38423fa5f768)

**Comment by Adnan-shariff** [comment]
Issue 6:

High school grade scale data when we add request is not received in my task approver of Add grade scale
 please check the file which i tried to add.
[high scholl scale graade.csv](https://github.com/user-attachments/files/16468424/high.scholl.scale.graade.csv)

**Comment by NavnathGunjal7** [comment]
> High school grade scale data when we add request is not received in my task approver of Add grade scale
> please check the file which i tried to add.

requested comming just data is not in sorted manner that's why not visible to you load all scales and search with date you will get the request

**Comment by Adnan-shariff** [comment]
> > High school grade scale data when we add request is not received in my task approver of Add grade scale
> > please check the file which i tried to add.
> 
> @Adnan-shariff requested comming just data is not in sorted manner that's why not visible to you load all scales and search with date you will get the request

@NavnathGunjal7 Hi Navnath it is not showing as we raise the request like in 5 minutes i refreshed i did not receive and sometimes it was showing as we raise

**Comment by Adnan-shariff** [comment]
Issue 1 : working as intended
issu2 : working as intended 
issue 3 : not required not an issue
issue 4: working as intended 
issue 5:  working as intended
