### ISSUE TITLE
Search in my work Date of assignment is not user readable

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#236]
**Describe the bug**
when we search appid in my work date of assignment is not user readable please refer screenshot

**Expected behavior**
it should be user readable
**Screenshots**
![image](https://github.com/user-attachments/assets/46853aec-bff7-488b-9b5c-859dbbc744a3)

**Comment by shivanim11** [comment]
@pankajsparihar please check this

**Comment by kartikatyagi** [comment]
Not working as expected 
We are not able to search the appid in the search bar it is giving us error message "Please provide an organization code"
Screenshots: 

![image](https://github.com/user-attachments/assets/1f5e149b-1709-4cc9-b490-7435b24d7caf)

**Comment by kartikatyagi** [comment]
working as expected 
screenshot : 
![image](https://github.com/user-attachments/assets/e4e1d20d-d142-41a5-b207-63521a4007a3)
