### ISSUE TITLE
when clicked on view in personal id, getting buffer sign

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#237]
When clicked on view in personal id getting buffer logo on that table/

Steps - 
1. open application 
2. click on view when personal id table appears
3. error

Test Data - 
ankit@vempower.org
App#slu1722428958226

Screenshot

![Screenshot from 2024-08-02 15-29-10](https://github.com/user-attachments/assets/66391049-fe7a-4058-80bc-365b185964b3)

**Comment by AnkitExcelerate** [comment]
@sl-repo please check it

**Comment by shivanim11** [comment]
Fixed.
able to view 
![Uploading image.png…]()
