### ISSUE TITLE
Add country for grade scale

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#239]
**Describe the bug**
here are sample files. and one country is " South Sudan " Also add this one

[Sample (9).csv](https://github.com/user-attachments/files/16504688/Sample.9.csv)
[Sample (8).csv](https://github.com/user-attachments/files/16504689/Sample.8.csv)

**Comment by kartikatyagi** [comment]
working as expected 
![image](https://github.com/user-attachments/assets/07afba9a-8410-45e9-8e86-6f7f70ba5bc6)
![image](https://github.com/user-attachments/assets/e2bd9685-999e-460e-87cf-ebcc7bf3ac79)
