### ISSUE TITLE
Search By Appid Issues 

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#240]
**Describe the bug**
When we search any appid it shows an error message

**Scope of the bug**
Search Appid Searchbar

**Steps to reproduce**
1.Search Appid by "Slu1564"

**Expected Behavior**
we should be able to fetch specific app 

**Actual Behavior**
we see error message 

**Screenshots**
![2024-08-07 15_59_09-Window](https://github.com/user-attachments/assets/9055cd42-53c6-474f-99e0-1a1efaab8d2c)
![2024-08-07 15_58_56-](https://github.com/user-attachments/assets/83fa6dae-faa9-4b20-8741-9284e11d0070)
![2024-08-07 15_58_30-](https://github.com/user-attachments/assets/ed3bf485-e7de-4a62-b1be-e02382a83850)

**Comment by Adnan-shariff** [comment]
Issue 2 : Search for CUA or Dpu in Search bar appid results in different Organisations

![2024-08-07 16_05_35-Window](https://github.com/user-attachments/assets/57a06a59-ddfa-432e-8776-f644843c1d48)
![2024-08-07 16_05_11-](https://github.com/user-attachments/assets/605a33a8-02a7-43e5-80a3-32696a420d01)

**Comment by MSGlobalShala** [comment]
This issue was happening because we have deployed front-end but not the back-end. Now it's working fine.
