### ISSUE TITLE
Type of evaluation: GPA: Incorrect Grade Display for Certain Score Ranges

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#243]
it is Missing the - and + plus values to display with the Grade 

For example country is India and grade scale is 10 CGPA.
If total CGPA = 7.42 then
 expected US GPA = 3.33 and US Letter Grade = B+ but the 
actual result is US GPA = 3.33 and US Letter Grade = B
So that means Letter Grade is incorrect.

**Comment by Adnan-shariff** [comment]
![2024-08-08 14_57_38-Mail](https://github.com/user-attachments/assets/349957fc-045f-4aba-8e61-5f63cf7ba4d6)

**Comment by MSGlobalShala** [comment]
@shivanim11 please assign someone for testing

**Comment by Adnan-shariff** [comment]
Working as intended hence closing this issue.
