### ISSUE TITLE
Daily APP Status

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#245]
**Describe the bug**
Blank Keyword is getting in email subject and table lines are not there 
![image](https://github.com/user-attachments/assets/cfbe795a-5211-4be4-a141-ad27f3036dfc)

![image](https://github.com/user-attachments/assets/c417e2c0-94a5-43db-ada8-fff4ca33b642)

**Comment by MSGlobalShala** [comment]
Today I got it correctly
![image](https://github.com/user-attachments/assets/f9924409-7084-4640-8abd-82a7e5f1e2ed)
