### ISSUE TITLE
chnage grade scale throwing error

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#250]
**Describe the bug**
change grade scale throwing error
![image](https://github.com/user-attachments/assets/4f7ad0f2-178b-4176-a768-8903d77ad56d)

**Comment by Adnan-shariff** [comment]
working as intended.

**Comment by MSGlobalShala** [comment]
@AnkitExcelerate please test

**Comment by AnkitExcelerate** [comment]
Working as expected
