### ISSUE TITLE
EmailTemplate# issues

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#26]
The request in task approver is coming when inserted users in mail_to of  EmailTemplate#ArchiveUserInitiatorReqApproved when ideally it should be in mail_to of  EmailTemplate#ArchiveUserApprover.

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/d57016f6-77ac-4914-9f6c-814e8e697294)

**Comment by shivanim11** [comment]
Fixed in dev
