### ISSUE TITLE
MFA: Multiple Issues 

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#261]
**Issue 1: Reset MFA**
**Describe the bug:**
 "Can't Scan the QR Code" option does not invalidate the old setup key generated OTP. Users can still log in with the old key even after resetting MFA.

**Scope of the bug:**
- Affects MFA setup and reset process.

**Steps to reproduce:**
1. Set up MFA using "Can't Scan the QR Code."
2. Reset MFA using the same option.
3. Attempt to log in with the old setup key.

**Expected Behavior:**
Old setup key should be invalidated after MFA reset.

**Actual Behavior:**
Old setup key remains valid and allows login.

**Screenshots:**

**Comment by Adnan-shariff** [comment]
**Issue 2: when we try to reset it should send code to User email**

**Comment by Adnan-shariff** [comment]
**Issue 3: when we enter wrong code it shows both mfa enabled message and also it shows code mismatch**
![2024-09-10 12_08_22-Window](https://github.com/user-attachments/assets/b4a37c4e-1639-49a1-8f60-bec9177ee0ba)

**Comment by Adnan-shariff** [comment]
**Issue 4: When the OTP field is left empty and the user clicks anywhere else on the screen, a green checkmark appears.**
![2024-09-10 12_51_39-Window](https://github.com/user-attachments/assets/1c5e87c2-95ad-4f57-a99e-522d0d1dc4ae)

**Comment by Adnan-shariff** [comment]
Issue 5: Login and click on Continue button it shows error message 
**Expected: Continue button should be disabled if we have not entered any otp in QR Code screen **
![2024-09-10 12_08_22-Window](https://github.com/user-attachments/assets/13aac07c-6c8f-4e67-8ac5-ee02d4ed59bb)
![2024-09-11 12_20_44-Mail](https://github.com/user-attachments/assets/9da9a64f-822b-45f6-850b-d76d6d952449)

**Comment by Adnan-shariff** [comment]
**Issue 6: when we enter same OTP after enabling MFA in component 2 to validate OTP when we enter same OTP error message is showing incorrect for same OTP** 
![2024-09-12 16_39_49-Window](https://github.com/user-attachments/assets/094e945f-6b24-421d-a7cf-7b39f90a6aae)

**Comment by Adnan-shariff** [comment]
DEV  Issues : 



Setupkey: **The "Copy" button functionality for the setup key is not working.**
![image](https://github.com/user-attachments/assets/5b8057fe-2c3e-4266-946d-2afc80ac05c1)

**Comment by Adnan-shariff** [comment]
![2024-09-23 12_20_02-Window](https://github.com/user-attachments/assets/ef9178bf-1ca1-4a65-bc46-dc8162a0ff48)

**Comment by Adnan-shariff** [comment]
Issue 8:
"_"
Remove underscore from "Reset_MFA" on the webpage

The "Reset_MFA" text on the webpage contains an underscore, which is unnecessary.  
![2024-09-23 12_33_04-Window](https://github.com/user-attachments/assets/ae14d495-c506-4c42-82dd-90db268f4fc9)

**Comment by Adnan-shariff** [comment]
Very high priority issues: **When we select Reset MFA, OTP notification should be sent for the user who is trying to reset for his email**

**Comment by Adnan-shariff** [comment]
**immediate priority for issue for user otp if we he is clicking on reset mfa  user should receive otp on his email**

**Comment by pankajsparihar** [comment]
added new Email template in DB EmailTemplate#SendResetMfaOTP

**Comment by Adnan-shariff** [comment]
**Issue 9: 
Reset MFA: 
In QR Code Screen 
Older OTP from the previous authenticator can be used**

**Comment by Adnan-shariff** [comment]
25/10/2024

DEV issues

Issue 7: still persist 



Setupkey: The "Copy" button functionality for the setup key is not working.

**Comment by Adnan-shariff** [comment]
28/10/2024

**Issue 10:**
**The email input field treats entries as case-sensitive, leading to a "user not found" error when email case varies.**

<img width="1440" alt="Screenshot 2024-10-28 at 12 51 57 PM" src="https://github.com/user-attachments/assets/fee71b8d-4f46-4ab2-90d7-5013b35f23e5">
