### ISSUE TITLE
Application List Page Enhancement

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#267]
**Describe the bug**
1. Improve the UI Add new button>> change the Text of button(it should be clear that upload appids to increase priority or high priority)
2. in the next pop-up we are showing that upload new applications>> it should be clear that upload appidsor high priority application.

**Expected behavior**
make changes on UI
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pankajsparihar** [comment]
fixed in user story itself.
