### ISSUE TITLE
Start and end date is incorrect for same day

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#270]
start date for same day start from 12-AM and end date ends for same day at 12-PM which is only 12 hour time frame.
We need to change end date with 11:59 PM for the same day

Steps - 
1. select same day for start date and end date
2. open network tab and click on get details button
3. check start and end date

![image](https://github.com/user-attachments/assets/d90936c8-7969-4af0-8c4f-012d78793635)

**Start date**
![image](https://github.com/user-attachments/assets/3b3eb483-e453-49dc-ae53-8c36e19c74d6)

**End Date**
![image](https://github.com/user-attachments/assets/6b4045b6-266e-4c2c-b30c-d7a2342493a5)

**Comment by NavnathGunjal7** [comment]
duplicate https://github.com/Globalshala/Eval-Bridge-bugs/issues/273
