### ISSUE TITLE
Leave record issues  with email and csv data 

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#271]
1. Username and timerange user added is not mentioned in the email, instead it displays {Username} & {Timerange}.

Steps-
a. Select start and end date
b. get details
c. send report
d. check email
![image](https://github.com/user-attachments/assets/c1be9b5f-9263-46aa-a1f8-12d96757f130)

2. The data rendered in UI is different or incomplete with data shared to user by csv
![image](https://github.com/user-attachments/assets/3452de5b-d358-41b8-827a-eeab10508a2c)
![image](https://github.com/user-attachments/assets/95f7e64e-a385-406e-a64f-2f7cbf56d92c)

**Comment by MSGlobalShala** [comment]
Fixed after deployment
![image](https://github.com/user-attachments/assets/3f837ae9-f167-4b42-8a2f-7f8bbbf6c9f5)
