### ISSUE TITLE
incorrect data is rendered in UI for leave records

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#272]
Selected start and end date as same and clicked on Get details button. The data which was loaded in UI was for different date i.e creation date for that request was different

steps - 
1. Select start and end date as 24-09-2024
2. click on get details
3. check the creation date

![image](https://github.com/user-attachments/assets/1ec4a350-fad3-4c99-b8c8-4a667d14f23d)

**Comment by MSGlobalShala** [comment]
As marked invalid
