### ISSUE TITLE
Upload csv feature is visible for team  leader

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#274]
The upload csv feature should only be there for admin and not for any other roles, we are getting that feature in team leader account

Steps -
1. login with team leader
2. check My Profile section
3. check for upload csv

Screenshot-
![image](https://github.com/user-attachments/assets/7369891d-882c-4954-9731-46647644fd39)

**Comment by kartikatyagi** [comment]
Working as expected fixed in dev 
![image](https://github.com/user-attachments/assets/05febaf0-a153-439c-8725-1b883d4b2a4d)

**Comment by AnkitExcelerate** [comment]
working as expected 
![Uploading image.png…]()
