### ISSUE TITLE
The timeframe in reports for start and end date

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#281]
Currently in our system, the timeframe between start and end date is maintained with end date i.e we cannot freely select the start date if we want to check the previous date applications.

Steps - 
1. Open start date in time based
2. try to freely select it.

Expected behaviour - 
We need to implement timeframe of 3 months from where we select the start date and accordingly the end date will be selected

Screenshot -
![image](https://github.com/user-attachments/assets/cb81bb49-28c6-49a9-86a9-1e16e5951061)

**Comment by NavnathGunjal7** [comment]
duplicate https://github.com/Globalshala/Eval-Bridge-bugs/issues/275

**Comment by AnkitExcelerate** [comment]
Working as expected
