### ISSUE TITLE
Sign-out Button Not Working

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#284]
**Describe the bug**
Sign-out button doesn't respond when clicked.

**Expected Behavior**
User should log out.

**Actual Behavior**
Nothing happens. User stays logged in.

![image](https://github.com/user-attachments/assets/932453c7-9e93-47c8-ac92-9f1313097c47)

**Comment by shivanim11** [comment]
Fixed on dev
