### ISSUE TITLE
"Verify Numeric Value Indication in 'Search By App ID' Input Field"

### ISSUE THREAD

**Issue by kartikatyagi** [Globalshala/Eval-Bridge-bugs#289]
**Describe the bug**
In the "Search by AppID" input field, it only accepts AppIDs with numeric values, but there is no indication or message specifying that only numeric values are allowed.

**Expected behavior**
There should be an indication that this input box only accept the numeric values
example: Select App Id (Search App Id's by numeric values only)

**Screenshots**
![image](https://github.com/user-attachments/assets/cbbdf131-20d2-4d6c-b649-bdb3fcbdb909)

**Comment by MSGlobalShala** [comment]
Please attach here the PR also, if the PR has been raised

**Comment by shivanim11** [comment]
Fixed on Dev
