### ISSUE TITLE
improvise assign apps to specific users from csv file

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#29]
improvise assign apps to specific users from csv file in backend optimize the code it's now working for 20+ application assignments to different users

**Comment by MSGlobalShala** [comment]
Working fine for me. I have tried with 37 applications
appIds,userEmails
App#slu1717997830230,pankaj@vempower.org
App#slu1717997831244,ae4d54b4-e56d-4e82-b117-e0dfe96256a6@mailslurp.net
App#slu1717997832294,santosh@vempower.org
App#slu1717997833341,adnan@vempower.org
App#slu1717997849809,mansi@vempower.org
App#slu1717997850893,santosh@vempower.org
App#slu1718000600002,akash@vempower.org
App#slu1718000601027,ankit@vempower.org
App#slu1718000602041,ankit@vempower.org
App#slu1718000603132,manish.shringi.58@gmail.com
App#slu1718000685917,manish.shringi.58@gmail.com
App#slu1718000688027,8271445f-793b-4bab-a8fd-073af3cb6527@mailslurp.net
App#slu1718000701191,kovacal545@mcatag.com
App#slu717258,Ranjith@globalshala.com
App#slu717428,dil08244@vogco.com
App#slu717427222,sabeakash125@gmail.com
App#slu1718006106449,ankitkumar@globalshala.com
App#slu1718006108513,karodi.globalshala@gmail.com
App#slu1718006123073,shivanimohite+test@globalshala.com
App#slu1718006124159,manish.shringi.58@gmail.com
App#slu1718007727115,6a0d28aa-55aa-49fb-a68c-aa7d720d9580@mailslurp.net
App#slu1718007728120,75349a38-8d86-4672-ba16-cf4723d493e8@mailslurp.net
App#slu1718007729141,2c53e8ea-8a54-4df4-9879-3b8cff251bae@mailslurp.net
App#slu1718007744193,ae4d54b4-e56d-4e82-b117-e0dfe96256a6@mailslurp.net
App#slu1718007972288,becf4ece-064a-48d6-b614-60c2b3214e59@mailslurp.net
App#slu1718007973297,becf4ece-064a-48d6-b614-60c2b3214e59@mailslurp.net
App#slu1718007974315,manish.shringi.58@gmail.com
App#slu1718007987964,6a0d28aa-55aa-49fb-a68c-aa7d720d9580@mailslurp.net
App#slu1718007988977,72c44637-b7c6-4aeb-af57-cd3478318c15@mailslurp.net
App#slu717427212,ae4d54b4-e56d-4e82-b117-e0dfe96256a6@mailslurp.net
App#slu1718009363207,manish.shringi.58@gmail.com
App#slu1718009364289,becf4ece-064a-48d6-b614-60c2b3214e59@mailslurp.net
App#slu1718009377079,manish.shringi.58@gmail.com
App#slu2636,8271445f-793b-4bab-a8fd-073af3cb6527@mailslurp.net
App#slu5565,c1e7d79f-8793-4987-a0ea-d43377d4988d@mailslurp.net
App#slu374829,b5d9d5ca-651a-4ceb-b0e1-220ba829db5f@mailslurp.net
App#slu672194,manish.shringi.58@gmail.com

**Comment by shivanim11** [comment]
Fixed we have tried more than 20 app its worked
