### ISSUE TITLE
overlapping leave pop up 

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#290]
when applied leave from 1st dec to 7 dec and again tried to apply leave between that time frame getting an pop up error that cannot apply leave between 30st nov to 7th dec.

Steps - 
1. Apply leave between 1st to 7th.
2. again try to apply between that date
3. check pop up error

Current behavior-
We are getting 1day back in start date in the error pop up

Expected behavior - 
The pop should have date in which leave was applied 

Screenshot - 
![image](https://github.com/user-attachments/assets/a4ffc90d-3ccd-4328-a950-d4747517538d)

**Comment by MSGlobalShala** [comment]
@AnkitExcelerate Are you able to apply leave for 30 Nov for the same account??

**Comment by AnkitExcelerate** [comment]
@MSGlobalShala yes, i am able to do that

**Comment by MSGlobalShala** [comment]
We have to add timezone in DB who is applying the opportunity
for example timezone-> 'Asia/Dubai', 'Australia/Sydney'

https://stackoverflow.com/questions/38399465/how-to-get-list-of-all-timezones-in-javascript

While displaying also we have to show timezone also -> No need to show time, the date with timezone will be enough according to me

**Comment by AnkitExcelerate** [comment]
Working as expected
![image](https://github.com/user-attachments/assets/bd02deae-15a1-4d14-9641-1d79a6cce78b)
