### ISSUE TITLE
College is not present then also adding comma before university

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#3]
**Describe the bug**
college is not there at time of evaluation. then also adding comma before university name. refer screenshot

**Expected behavior**
comma should not be there if college is not present
**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/d4173593-1bbc-4244-8757-286a92078220)

**Comment by AnkitExcelerate** [comment]
Working
