### ISSUE TITLE
test system with given  report files for depaul university

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#30]
[Chandra Mouli Medicherla_074961365.pdf](https://github.com/Globalshala/Eval-Bridge-bugs/files/14495244/Chandra.Mouli.Medicherla_074961365.pdf)
[Ezra Musondoli_132001887.pdf](https://github.com/Globalshala/Eval-Bridge-bugs/files/14495245/Ezra.Musondoli_132001887.pdf)
[Nora Hayford_641569516.pdf](https://github.com/Globalshala/Eval-Bridge-bugs/files/14495249/Nora.Hayford_641569516.pdf)

**Comment by shivanim11** [comment]
Fixed on dev

**Comment by shivanim11** [comment]
duplicate #80
