### ISSUE TITLE
Type of Evaluation: PG:  "Number Of Repeats" and "Duration Of Program" Fields Not Accepting Numerical Input

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#302]
**Describe the bug**  
The  "Number Of Repeats" and "Duration Of Program"  fields are not allowing to input numbers.

**Scope of the bug**  
Type of evaluation> **Dual degree** > **Evaluate PG**

**Steps to reproduce**  
1. Go to evaluation of PG with "Number Of Repeats" and "Duration Of Program"
2. Try entering numbers in both fields.

**Expected Behavior**  
Both fields should accept numerical values.

**Actual Behavior**  
The fields do not accept any numbers, preventing form submission.

**Screenshots**  
![image](https://github.com/user-attachments/assets/5b848860-a39b-4517-9ca6-780353115c04)

**Comment by MSGlobalShala** [comment]
Hi @Adnan-shariff 
It's working for me. I am able to type to Numeric value in both the fields and we can not type the alpha-bates and special character which seems correct to me

**Comment by Adnan-shariff** [comment]
Hi @MSGlobalShala please check for dual degree in Evaluate PG

**Comment by AnkitExcelerate** [comment]
Working as expected
