### ISSUE TITLE
Review: Click on any review App: "Unexpected Errors" and  Entire system breaks 

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#303]
**Describe the bug**  
Selecting an AppID for review (either new or in progress) shows unexpected errors. Clicking "My Work" causes the application to crash.

**Scope of the bug**  
**Review**> Open any Appid which is in Review new or Reviewprogress 

**Steps to reproduce**  
1. Click "Review."
2. Select any AppID (new or in-progress).
3. Errors appear.
5. Click "My Work," and the app crashes.

**Expected Behavior**  
- When selecting a  Review new or  Review progress Appid  it should open without errors for further actions.

**Actual Behavior**  
Errors occur when selecting an AppID for review, 
and the app crashes upon clicking "My Work." from review 

![2024-10-17 14_05_17-Settings](https://github.com/user-attachments/assets/2acd7359-b315-4396-a780-30efff7b32a0)
![2024-10-17 14_05_31-Settings](https://github.com/user-attachments/assets/9cfa36e2-989f-455b-9492-0498c5f4f808)
![2024-10-17 14_06_57-Settings](https://github.com/user-attachments/assets/016fb31f-a7eb-4e11-91f6-c3fbeda65824)

**Comment by Adnan-shariff** [comment]
![image](https://github.com/user-attachments/assets/ef9ceb1e-269e-400a-8e30-32c4ab367e19)

**Comment by AnkitExcelerate** [comment]
Working as expected
