### ISSUE TITLE
GPA check in incomplete transcript

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#31]
Getting invalid gpa error in incomplete transcript.

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/2594e0b6-26f0-485b-8118-420388f2950f)

**Comment by NavnathGunjal7** [comment]
@AnkitExcelerate please test and close if resolved

**Comment by shivanim11** [comment]
Fixed in dev
