### ISSUE TITLE
Team lead: My task approver Options 

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#323]
The "My Task Approver" section includes "Grade Scale Archive" and "Grade Scale Edit,""Add Grade Scale." Should this option be present for the Team Lead, or is it unnecessary?

**Team lead > My task approver consists of :**
Grade scale archive 
Grade scale edit 
Add grade scale 

![2024-11-08 11_31_59-Window](https://github.com/user-attachments/assets/30cdd2d0-870f-4709-9ff5-39816a46d2d7)
![2024-11-08 11_27_15-](https://github.com/user-attachments/assets/6a4a2f25-c8e2-4b8a-885b-cd719211dec8)

**Comment by MSGlobalShala** [comment]
It's fine because the approver can be the team-leader for these categoty. Confirmed with Deeksha.
