### ISSUE TITLE
Create scale data issue

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#34]
**Describe the bug**
Kindly find the attached doc link to view all issues which are found during testing

https://docs.google.com/document/d/1GLJAa-yZLEAqJn9L-Ik9WXzhLO_K0ATPYNYyhQJLlpM/edit?usp=sharing

**Comment by NavnathGunjal7** [comment]
@shivanim11 please take latest pull and test let me know if there are still issues some UI improvisation will be done later

**Comment by Adnan-shariff** [comment]
working as intended .
