### ISSUE TITLE
marking appid incomplete after evaluation

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#35]
After the evaluation process appid is sent for review and in review marking that application as incomplete and sending it to next level. Currently, we are getting report and entry in csv file with GPA and everything.

Steps - 
1. Evaluate 1 appid
2. Send to Next level
3. Now in review, mark it as incomplete
4. Send to next level
5. Master uplaod

Expected Result - Report should not generate for that appid and entry in the csv report should be there as incomplete.

**Comment by NavnathGunjal7** [comment]
@AnkitExcelerate  please test if resolved close it if not resolve send me message

**Comment by shivanim11** [comment]
Fixed in dev
