### ISSUE TITLE
refresh token creating for new users without checking the signed in box

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#36]

**Comment by NavnathGunjal7** [comment]
@AnkitExcelerate please test if resolved close it

**Comment by Adnan-shariff** [comment]
working as intended .
![2024-06-26 18_19_10-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/ef0e7764-9456-4d2f-85c8-95c08a38800f)
