### ISSUE TITLE
Grade Scale Issue

### ISSUE THREAD

**Issue by karodisuresh** [Globalshala/Eval-Bridge-bugs#37]
1.In search function after removing the search data it will not be neutralize it is stay in the filter mode 
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/103185383/74fc198d-1825-46db-a425-9500082adc3c)
after it is 
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/103185383/fde0ca58-07f9-44ac-b298-d6af227192cc)

2.In search filter it will take only uppercase it does not identify the lowercase
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/103185383/d39f5de2-b9cc-42ca-91d5-1728296b149e)

**Comment by NavnathGunjal7** [comment]
@karodisuresh please test again it's resolved UI improvisation will be done later please check functionality

**Comment by shivanim11** [comment]
Fixed in dev
