### ISSUE TITLE
Grade Scale Archive Request

### ISSUE THREAD

**Issue by karodisuresh** [Globalshala/Eval-Bridge-bugs#38]
1. When you give the request to the grade scale archive I am getting the count instead of the My task Approver
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/103185383/0e822374-8b0c-460b-bd30-3fbf0e779100)

2.But we not get the request in the "GradeScaleArchive"  Active , and time also not with suffiecent format there is no order for that 
![ image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/103185383/93b524e0-0159-41b4-abce-b882c3f66a4e)

**Comment by mansi38299** [comment]
Auto Scroller is not working as well

**Comment by NavnathGunjal7** [comment]
please test again

**Comment by shivanim11** [comment]
Fixed on dev
