### ISSUE TITLE
Upload New Grade Scales issue

### ISSUE THREAD

**Issue by karodisuresh** [Globalshala/Eval-Bridge-bugs#39]
1.When you upload the file ,the format of file like jpg,pdf,Textformat etc, We are getting the error message  same like csv file,
 # So in that case write a condition like  "this format does not exit". 
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/103185383/b8bc3aa9-68ba-441b-8811-e771011247a0)

**Comment by NavnathGunjal7** [comment]
please test this again take latest pull

**Comment by shivanim11** [comment]
Fixed in dev.
added check to upload file
