### ISSUE TITLE
Send to next level error in Highschool application (General)

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#41]
When selected General evaluation in High school application and tried to send it to next level after filling the data, getting error.

Screenshot- 
![Screenshot from 2024-03-23 00-25-16](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/ac26be62-8bbd-448c-b722-46f33a84f5ec)

**Comment by shivanim11** [comment]
Fixed in dev
