### ISSUE TITLE
My Team resolution problem 

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#45]
1. For different screen resolutions scroll bar was not working
2. Change description screen reaulution from setting to 25℅, 50℅
3. Also check 50% zoom in zoom out

**Comment by NavnathGunjal7** [comment]
@AnkitExcelerate  its merged in master you can test in master branch

**Comment by shivanim11** [comment]
@NavnathGunjal7  can you please specify what was the issue here.

**Comment by NavnathGunjal7** [comment]
> @NavnathGunjal7  can you please specify what was the issue here.

Updated description

**Comment by shivanim11** [comment]
scroller is working for more than 50%. not working if we have reduced than 50%
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/93dcadbf-59cd-46c1-996c-a33a6437c712)

**Comment by NavnathGunjal7** [comment]
@shivanim11 please verify and close

**Comment by shivanim11** [comment]
Fixed
