### ISSUE TITLE
GradeScale Filtering UI 

### ISSUE THREAD

**Issue by karodisuresh** [Globalshala/Eval-Bridge-bugs#49]
For the filtering UI we need to modify the below picture  format 
![Screenshot 2024-03-13 110346](https://github.com/Globalshala/Eval-Bridge-bugs/assets/103185383/237600d7-0b1d-4965-b46c-c9e8dbf385cf)
Instead of the filtering we need add drop down for the AND OR buttons

**Comment by shivanim11** [comment]
Fixed
