### ISSUE TITLE
Redoing master upload without AppId's

### ISSUE THREAD

**Issue by RajdeepGlobalshala** [Globalshala/Eval-Bridge-bugs#50]
In redoing master upload, whenever we are trying to click on the "Appis Master Upload" button without entering any AppId, a toast message appears: "Request sent to AppIds master upload" while there is no AppId in the input box.
![Screenshot 2024-04-02 153814](https://github.com/Globalshala/Eval-Bridge-bugs/assets/157602910/07b551e5-20ad-411e-933d-d55cb04c4f6c)

1. Run the 'userstory-redoingMaster' branch in your local system for both the frontend and backend repositories.
2. Go to 'My Profile'
3. Click on 'Actions'
4. Scroll down to 'Redo Master Upload'
5. Click on 'AppIds Master Upload'

If AppIds are not present in the input box, then we expect a toast message (e.g., "AppId's are not present" or "Please enter AppId") or something like that.

**Comment by ipankajparihar** [comment]
resolved

**Comment by shivanim11** [comment]
Fixed
