### ISSUE TITLE
Redoing master upload for AppId's with incomplete transcript

### ISSUE THREAD

**Issue by RajdeepGlobalshala** [Globalshala/Eval-Bridge-bugs#56]
Whenever we are trying to do redoing master upload for those AppId which are in complete pool with incomplete transcript then the toast message showing "Request sent for AppIds master upload" and email is not received
![Screenshot 2024-04-08 151945](https://github.com/Globalshala/Eval-Bridge-bugs/assets/157602910/5c5e71e3-1e68-4d75-b840-1a17b98ec54e)

1. Run the 'userstory-redoingMaster' branch in your local system for both the frontend and backend repositories.
2. Go to 'My Profile'
3. Click on 'Actions'
4. Scroll down to 'Redo Master Upload'
6. Click on 'AppIds Master Upload'

**Comment by shivanim11** [comment]
Fixed in dev
