### ISSUE TITLE
Redoing master upload for AppId's with complete transcript

### ISSUE THREAD

**Issue by RajdeepGlobalshala** [Globalshala/Eval-Bridge-bugs#57]
Whenever we are trying to do redoing master upload for those AppId which are in complete pool with complete transcript then toast message showing "Request sent for AppIds master upload" after lot of loading and email is not received
![Screenshot 2024-04-08 152850](https://github.com/Globalshala/Eval-Bridge-bugs/assets/157602910/d1d6d3b6-c3e6-47d3-99f9-1a2768075a77)
![Screenshot 2024-04-08 153152](https://github.com/Globalshala/Eval-Bridge-bugs/assets/157602910/34014f68-0b7f-4935-b1c5-4be76df03195)

1. Run the 'userstory-redoingMaster' branch in your local system for both the frontend and backend repositories.
2. Go to 'My Profile'
3. Click on 'Actions'
4. Scroll down to 'Redo Master Upload'
5. Click on 'AppIds Master Upload'

**Comment by mansi38299** [comment]
Please verify and confirm

**Comment by shivanim11** [comment]
Fixed
