### ISSUE TITLE
Redoing master upload for those AppId's which are in eval_new, eval_inProgress, review_new, review_inProgress(eval pool or review pool)

### ISSUE THREAD

**Issue by RajdeepGlobalshala** [Globalshala/Eval-Bridge-bugs#59]
Whenever we are trying to do redoing master upload for those AppId which are in eval_new, eval_inProgress, review_new, review_inProgress it means that if AppId's are in eval pool or review pool then toast message showing "Request sent for AppIds master upload" after a lot of loading and email is not received
![Screenshot 2024-04-09 150422](https://github.com/Globalshala/Eval-Bridge-bugs/assets/157602910/9328cbc4-eadd-4b70-83cb-ec79bcbe214a)
![Screenshot 2024-04-09 150742](https://github.com/Globalshala/Eval-Bridge-bugs/assets/157602910/47b2a1d6-ac95-4a96-905a-23522c9044a9)

1. Run the 'userstory-redoingMaster' branch in your local system for both the frontend and backend repositories.
2. Go to 'My Profile'
3. Click on 'Actions'
4. Scroll down to 'Redo Master Upload'
5. Click on 'AppIds Master Upload'

**Comment by shivanim11** [comment]
Fixed
