### ISSUE TITLE
Create user for same user code

### ISSUE THREAD

**Issue by RajdeepGlobalshala** [Globalshala/Eval-Bridge-bugs#60]
Whenever we are creating user by filling up the details which are given in the create user page like First Name, Last Name, Email address, Employee Organisation, Employee Code, Evaluate Capacity, Review Capacity, and Employee Role in the input fields then there  is two fields are unique Email address and Employee Code or user code but there is two user created with same user code(mt-20)
![Screenshot 2024-04-09 150919](https://github.com/Globalshala/Eval-Bridge-bugs/assets/157602910/9edab0e6-a5a7-4063-8cdc-86fe5f952c1f)

1. Go to 'http://13.127.150.18:3000/dashboard'
2. Click on 'User icon'
3. Click on 'My Team'
4. Filter by 'user_code'
5. enter 'mt-20' in search bar

**Comment by ipankajparihar** [comment]
Error was not reproducible, and it's showing the correct error message about the duplicate empCode.

**Comment by Adnan-shariff** [comment]
working as intended, please check the screenshot attached.


![create_new_user_qa verified1](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/b8169cf2-2cbb-4c3b-9bad-b6e4f59312ea)
