### ISSUE TITLE
Redoing mater upload for all Appid's 

### ISSUE THREAD

**Issue by RajdeepGlobalshala** [Globalshala/Eval-Bridge-bugs#61]
Whenever we are trying to do redoing master upload for any AppId then toast message showing "Route not found" and there is lot of loading also email is not received
![Screenshot 2024-04-11 090456](https://github.com/Globalshala/Eval-Bridge-bugs/assets/157602910/ff11b72a-e3fe-45f2-86ac-9ee901ab95eb)
![Screenshot 2024-04-11 085921](https://github.com/Globalshala/Eval-Bridge-bugs/assets/157602910/9486b0b2-95cc-4462-be67-edde74886892)
![Screenshot 2024-04-11 085735](https://github.com/Globalshala/Eval-Bridge-bugs/assets/157602910/3dbb357f-38b6-428e-ad4f-f2d39b12038c)

1. Run the 'userstory-redoingMaster' branch in your local system for both the frontend and backend repositories.
2. Go to 'My Profile'
3. Click on 'Actions'
4. Scroll down to 'Redo Master Upload'
5. Click on 'AppIds Master Upload'

**Comment by shivanim11** [comment]
Fixed in dev
