### ISSUE TITLE
decimals in credits, cbc page api return empty object it should return updated cbc data object

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#63]
**Describe the bug**
decimals in credits, cbc page api return empty object it should return updated cbc data object

**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/108262338/8832e052-b502-409d-abae-b927e6c8aa24)

**Comment by shivanim11** [comment]
Fixed in Dev
