### ISSUE TITLE
duplicate entries in complete pool

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#64]
**Describe the bug**
we are getting duplicate entries in complete pool

1. don't know root cause need to find it
2. for tempory fix we are not considering duplicates we will ignore it and generate csv file without duplicates
3. duplicate values comming in complete pool
4. To test = all journey of application for 2-3 apps

**Comment by NavnathGunjal7** [comment]
@AnkitExcelerate  please test and close

**Comment by Adnan-shariff** [comment]
working as intended we are not seeing duplicates in complete pool .
![2024-06-27 16_20_39-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/16298e3e-c662-4458-81bc-91f635426d4a)
