### ISSUE TITLE
send back to evaluator issues

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#67]
**Describe the bug**
1. Send back to evaluator not working if Evaluator not exist and other user having capacity then its assigning app to archived user i.e. original evaluator
2. Send back to evaluator not working if Evaluator not exist and other user don't have capacity then its assigning app to archived user i.e. original evaluator
3.  application maintaining status 6 when we sending back to evaluator its not correct modify its according to eval_inprogress

**Expected behavior**
1. it should assign other user who have capacity
2. it should assign other users forcefully not to original evaluator
**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/ea3b03a7-6848-4a9c-977e-b1396f30fa04)

**Comment by AnkitExcelerate** [comment]
@NavnathGunjal7  Application got assigned to the archive user

**Comment by AnkitExcelerate** [comment]
Working in dev
