### ISSUE TITLE
Redoing master upload issue

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#68]
**Describe the bug**
1. if appid not exist then not getting high priority issue.
2. if id format is incorrect "appslu12" then we are not getting any email regarding that appid.

**Expected behavior**
1. should get high priority email
2. should get email that format is incorrect/ highpriority email

**Comment by shivanim11** [comment]
@NavnathGunjal7 Are we adding any email format for second issue?

**Comment by NavnathGunjal7** [comment]
> @NavnathGunjal7 Are we adding any email format for second issue?

No we are rwmoving such IDs
