### ISSUE TITLE
invalid case issue

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#7]
**Describe the bug**
1. OM can be 0 if we entered OM as 0 and try to save this data throwing error.
2. if we enter credit 0 then also its throwing error
3. the error we are showing for above scenarios those are not clear to end User. kindly modify those 

**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/2154698c-d94c-42c8-be4c-315c6d8cc10e)

**Comment by mansi38299** [comment]
Please verify this

**Comment by AnkitExcelerate** [comment]
Working in dev

**Comment by mansi38299** [comment]
@AnkitExcelerate Please verify and get it approved from shivani and accoridngly close

**Comment by shivanim11** [comment]
we are not able to add decimals in OM
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/0ab4a443-ad2a-4f9c-a382-d8793af85989)

**Comment by AnkitExcelerate** [comment]
Able to save data in first iteration but got pop up "No changes save" when tried second time and after adding more rows with 0 as OM got error 
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/a3a23dfa-af0b-41f4-ae99-4cdf7982fc53)

**Comment by AnkitExcelerate** [comment]
Working in dev
