### ISSUE TITLE
Fetch cbc data not found issue

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#71]
**Describe the bug**
scenario: if parallelly verifying applications which having same major and university in that case user1 cleared cbc data and same time user 2 trying to fetch it in that case its throwing no data found issue.

**Expected behavior**
it should fetch data of latest modified and which has cbc data
**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/16a2b5ad-5a8d-4edf-8e1f-17b019a55bac)

**Comment by AnkitExcelerate** [comment]
Working in dev
