### ISSUE TITLE
Feedback Page not visible

### ISSUE THREAD

**Issue by mansi38299** [Globalshala/Eval-Bridge-bugs#72]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ipankajparihar** [comment]
Where should this feedback page link be placed? in main menu or somewhere else??

**Comment by mansi38299** [comment]
<img width="1440" alt="image" src="https://github.com/Globalshala/Eval-Bridge-bugs/assets/79189076/92d67f49-127b-4952-9b0d-02547b033077">
On clicking of this icon, it should open feedback page,

**Comment by Adnan-shariff** [comment]
Working as expected feedback page button is functioning as intended we are directed to feedback page.

![Screenshot (106)](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/91b764ea-f6dc-45eb-a38e-c0b14b3fc025)

**Comment by shivanim11** [comment]
Page is visible not able to submit request
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/0e6de2bc-727c-4a73-ae8e-a28e18bccab0)

**Comment by shivanim11** [comment]
Fixed
