### ISSUE TITLE
undefined in master upload cron job user name

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#76]
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/108262338/d3ba3146-60d8-4748-b3b6-c6452f84f673)

**Comment by Adnan-shariff** [comment]
working as intended. 
![2024-06-27 16_57_59-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/25d96800-7184-41fa-9911-2b349ad100be)
![2024-06-27 16_57_39-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/2a193432-fcc4-4f7a-8b01-310215b16cb4)

**Comment by NavnathGunjal7** [comment]
@Adnan-shariff trigger this with cron job there is documentation Available on slab or disscuss with @AnkitExcelerate

**Comment by AnkitExcelerate** [comment]
Working as expected
