### ISSUE TITLE
Status mismatching in review state

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#77]
**Describe the bug**
scenario: take fresh appid. evaluate with 2 degree and send to next level open it from reviewer side and check in response appid status is 2. because of this send back to evaluator button is not there.

**Expected behavior**
if appid is assigned to reviewer status should not 2
**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/5df7d17f-cd90-4e3c-887f-a85d7376a74a)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Adnan-shariff** [comment]
issue persist still, please check the screenshot attached. 
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/e9994c9c-a039-48ad-9abc-214350d7e4c5)

**Comment by NavnathGunjal7** [comment]
> issue persist still in dev, please check the screenshot attached. 
> ![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/e9994c9c-a039-48ad-9abc-214350d7e4c5)
> 

Please check db as well for relationship of app I'd and user status should be 2

**Comment by shivanim11** [comment]
Fixed
