### ISSUE TITLE
ug out of pg out of calcualte only when scale is changed

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#78]
**Describe the bug**
ug out of pg out of calcualte only when scale is changed
1. it changing in every next call of type of eval page
**To Reproduce**
1. from type of eval click on next check API call you can see pg out of ug out of sent to backend 
that is unnecessary
2. expected : it should only be sent when we are changing scale

**Comment by pankajsparihar** [comment]
checked not found the issue
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/170698299/7ce39f9f-e534-4714-be02-0981904b3ebd)

**Comment by shivanim11** [comment]
@pankajsparihar 
issue is not fixed
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/46c441ed-f281-426c-b03c-de9b4ddcfefa)

**Comment by shivanim11** [comment]
Fixed
