### ISSUE TITLE
Time based US issues

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#79]
**Describe the bug**
https://docs.google.com/document/d/1Zvgu5gwgnx2SdqcfMVyjveA57Hv2pf1bd4ZzgYGMooc/edit

**Comment by NavnathGunjal7** [comment]
@Adnan-shariff , @AnkitExcelerate  @shivanim11  please test and close

**Comment by shivanim11** [comment]
Fixed
