### ISSUE TITLE
Should able to edit college name or any dropdowns

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#8]
**Describe the bug**
1. user have created a college name and he/she wants to edit that (mistake in spelling and more)  so for now he have to create new record. we should provide the edit access to them via pointer. like select the dropdown value and edit that and submit.
make this for each dropdowns

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/efc89c43-1d41-44f3-ad88-3716d8b94007)

**Comment by mansi38299** [comment]
College,University,State,city,credential,Additonal Comments
