### ISSUE TITLE
click on my work throwing error

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#82]
**Describe the bug**
clicking on my work throwing error 
shivani@vempower.org
test@123

**Expected behavior**
it should open my work 
**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/10402eba-c154-4df6-ac4e-d03f9a97e875)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Adnan-shariff** [comment]
Working as expected in dev please check the screenshot attached.


![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/034694f0-16a8-4cf0-b479-344865d371a1)
