### ISSUE TITLE
logout api is not getting called when we are sign out

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#83]
**Describe the bug**
click on sign out button logout api is not getting called

**To Reproduce**
1. click on sign out button logout api is not getting called

**Comment by Adnan-shariff** [comment]
![Screenshot 2024-05-08 114324](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/fe98abe6-dc17-438c-815f-7555093c5af7)

reopening the bug by adding a screenshot as issue persist.

**Comment by Adnan-shariff** [comment]
![Screenshot 2024-05-08 114324](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/12c12b2a-a8fd-431f-a583-36af1fca884f)

Issue persist adding screenshot of the network tab.

Expected Behaviour: The sign-out API should be called.

**Comment by shivanim11** [comment]
Fixed 
![image](https://github.com/user-attachments/assets/2231d755-79d2-49b2-a043-fe1010bb6696)
