### ISSUE TITLE
complete pool to upload pool indexing issue

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#84]
**Describe the bug**
1. if there are more than one org ids are there in complete pool
2. and if we do master upload of one organisation wrong ids are getting removed from complete pool

**Comment by Adnan-shariff** [comment]
triggered  master upload only for slu 9635845
 from below and other org id was not removed please check the screenshot attached.
![2024-06-27 16_20_39-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/8a492896-8c0b-4ccc-a3ed-ce59c7e4f47a)
![2024-06-27 16_22_21-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/790affb1-e0ae-4fa4-964e-faf852324181)
![2024-06-27 16_22_11-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/0d1639a9-d220-4703-a545-58b76e4c8f11)
