### ISSUE TITLE
dupliates in eval pool, avoid deletion and updation of ug_gpa, ug_gpa letter grade at same time

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#85]
**Describe the bug**
1. if there are duplicates in csv file it was creating duplicates in eval_pool
2. if there was a total cgpa already there in data and it's grade general eval and we were changing education level
at that time ug_scale and ug_country is made empty and gpa are also remove but same time general gpa was getting calculated

<img width="1440" alt="MicrosoftTeams-image (9)" src="https://github.com/Globalshala/Eval-Bridge-bugs/assets/108262338/18fa8f1e-c812-4670-87dd-2361e7c9d554">

**Comment by Adnan-shariff** [comment]
working as intended. 
1.duplicate apps are not present in eval_pool
2.when we change education level we are not facing any issue 
![2024-06-27 13_28_40-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/57d2c1c3-a524-405f-a8f8-da3015f73bda)
![2024-06-27 13_28_25-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/a814cff0-7f14-4cf4-b905-584b1e844fb7)
![2024-06-27 13_28_16-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/33b841f5-5343-49fe-a737-32d1db3c3368)
