### ISSUE TITLE
Evaluation: App#cua268985 - Fill the details - Click on Save -an error message is displayed: "One or more parameter values are not valid"

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#89]
**Describe the bug**
When attempting to proceed by clicking on the "Save" button after entering the following evaluation details, the application displayed an error message "One or more parameter values are not valid. A value specified for a secondary index key is not supported. The AttributeValue for a key attribute cannot contain an empty string value. IndexName: country-gradeScale, IndexKey: country"

**To Reproduce**
Test case 1:
Scope: Evaluation> Select cua268985
Organization: Catholic University of America
AppId: 268985
Type of Evaluation: **General Evaluation**
Degree of Evaluation: **Undergraduate**
Ug Country: Afghanistan
Ug Scale: 6 GPA Scale
Complete Transcript Available: Yes
Degree Awarded: Yes
Any additional credentials for evaluation?: No
First Name: User1
Last Name: test2
College: Vidyakendram Degree College
University: Acharya Nagarjuna University
City: Bijnor
State: Uttar Pradesh
Credential Name: Bachelor of Science
Major: nkjnk
Admission Year: 2023
Graduating Year: 2026
Program Duration: 3
Total CGPA: 3
No Of Repeats: 0
US Degree Equivalency: US bachelor's degree
Accreditation: Yes
Additional Comments: None

Test case 2:
Scope: Evaluation> Select cua268985
Organization: Catholic University of America
AppId: 268985
Type of Evaluation: **Course By Course** 
Degree of Evaluation: **Undergraduate**
Ug Country: Afghanistan
Ug Scale: 6 GPA Scale
Complete Transcript Available: Yes
Degree Awarded: Yes
Any additional credentials for evaluation?: No
First Name: User1
Last Name: test2
College: Vidyakendram Degree College
University: Acharya Nagarjuna University
City: Bijnor
State: Uttar Pradesh
Credential Name: Bachelor of Science
Major: nkjnk
Admission Year: 2023
Graduating Year: 2026
Program Duration: 3
Total CGPA: 3
No Of Repeats: 0
US Degree Equivalency: US bachelor's degree
Accreditation: Yes
Additional Comments: None

Test case 3:
Scope: Evaluation> Select cua268985
Organization: Catholic University of America
AppId: 268985
Type of Evaluation: **Course By Course** 
Degree of Evaluation: **Undergraduate and Postgraduate**
Ug Country: Afghanistan
Ug Scale: 6 GPA Scale
Complete Transcript Available: Yes
Degree Awarded: Yes
Any additional credentials for evaluation?: No
Pg Country : India
PgScale: 10 CGPA Scale
Complete Transcript Available: Yes
Degree Awarded: Yes
Any additional credentials for evaluation?: No
Click : Next 

Test case 4:
Scope: Evaluation> Select cua268985
Organization: Catholic University of America
AppId: 268985
Type of Evaluation: **General Evaluation**
Degree of Evaluation: **Undergraduate and Postgraduate**
Ug Country: Afghanistan
Ug Scale: 6 GPA Scale
Complete Transcript Available: Yes
Degree Awarded: Yes
Any additional credentials for evaluation?: No
Pg Country : India
PgScale: 10 CGPA Scale
Complete Transcript Available: Yes
Degree Awarded: Yes
Any additional credentials for evaluation?: No
Click : Next 

**Actual behaviour** : Error message is displayed "One or more parameter values are not valid. A value specified for a secondary index key is not supported. The AttributeValue for a key attribute cannot contain an empty string value. IndexName: country-gradeScale, IndexKey: country"

**Expected behavior**
The application should advance without any error.

**Screenshots**
![Screenshot (72)](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/d7773af6-69f9-4048-9bb4-b42745c33210)

**Comment by kartikatyagi** [comment]
All test cases are working as expected
screenshot attached : 
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/14c1da40-7491-43c0-89a7-082f5925a867)

**Comment by Adnan-shariff** [comment]
working as intended.
