### ISSUE TITLE
If user change scale type then OM and MM should change accordingly

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#9]
**Describe the bug**
user selected 4gpa scale and enter number of records in cbc. then he has changed scale type to letter grade. then cbc page should work accordingly. it is showing previous OM and MM on same page

**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/bc22855a-a7a1-4bcc-b584-adfcb1016db7)

**Comment by AnkitExcelerate** [comment]
Working in dev

**Comment by mansi38299** [comment]
@AnkitExcelerate  Please verify and get it approved from shivani and accoridngly close

**Comment by shivanim11** [comment]
Fixed
