### ISSUE TITLE
Personal id User story issues

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#90]
**Describe the bug**
1. Scenario: once we restore the app data based on the personal id and clicked on next and back gain to type of evaluation page its popping out the table again and if we restore any other app data then its getting updated. refer attached video link.
2.  make table scrollable and to full size

**To Reproduce**
4. Click on '....'
5. Scroll down to '....'
6. See error

**Expected behavior**
it should not suggest table again 
**Screenshots**
https://www.loom.com/share/57b5b4ece95a45049b67f3fbbc077fca?sid=1c00d7a8-718f-47e8-8aca-7bec1be497d2

**Comment by pankajsparihar** [comment]
its working as expected

**Comment by shivanim11** [comment]
Fixed on Dev
