### ISSUE TITLE
Dpu: Academic Evaluation report: Letter Grade Column Added Despite 10 CGPA Scale Selection in report 

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#92]
**Describe the bug**
After selecting the CGPA scale of 10 for both Undergraduate (UG) and Postgraduate (PG) a letter grade column is added to the Academic Evaluation report.

**Scope of the bug**
**Evaluation >Depual University >Appid: dpu54621**

**Steps To Reproduce**
Select Evaluation:
Select Depual University
Enter the following details:
AppId: dpu54621
Organization: DePaul University
Evaluation Level: Global Graduate Courses
Degree of Evaluation:
**- Undergraduate**
**- Postgraduate**
Type of Evaluation: **Course by Course**
UG Country: India
UG Scale: 10 CGPA Scale
PG Country: India
PG Scale: 10 CGPA Scale
UG Details:
Complete Transcript Available: Yes
Degree Awarded: Yes
Any additional credentials for evaluation?: No
PG Details:
Complete Transcript Available: Yes
Degree Awarded: Yes
Any additional credentials for evaluation?: No
Add the following student details:
APP ID: 54621
First Name: Test
Last Name: user8
College:
MYCEM (For UG)
VVIET (For PG)
University: VTU
City:
Amravati (For UG)
Mysore (For PG)
State:
Hyderabad (For UG)
Karnataka (For PG)
Credential name:
BE (For UG)
MTECH (For PG)
Major:
EC (For UG)
Mechanical (For PG)
Admission Year: 2020 (For UG), 2024 (For PG)
Graduating Year: 2023 (For UG), 2026 (For PG)
Program Duration: 3 (For UG), 2 (For PG)
Total CGPA: 2 (For UG), 7.5 (For PG)
No Of Repeats: 0
US Degree Equivalency: US bachelor's degree
Accreditation: Yes
Additional Comments: None
Generate the evaluation report.

Actual behaviour: 
Observe that the "Letter Grade" column is added to the report, despite selecting the 10 CGPA scale for both UG and PG evaluations.

Expected Behavior:
The letter grade column should not be displayed in the academic evaluation report when the 10 CGPA scale is selected for both UG and PG evaluations.

Please check the screenshot attached. 

**Screenshots**
![lettergradebug](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/45a52422-50fc-4119-b5fb-4c15fb77cd18)

**Comment by Adnan-shariff** [comment]
Working as intended please check the screenshot attached.

![92](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/7383db75-02d0-4b3e-847c-ead3ba8fc60a)
![93 333333](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/c1c9e457-65c4-415e-993a-6008ceb54561)

**Comment by mansi38299** [comment]
@Adnan-shariff  Please close if it is resolved

**Comment by Adnan-shariff** [comment]
Changes are not required Dpu should have letter grade column as intended hence closing the issue.
