### ISSUE TITLE
User archive request is not showing 

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#93]
**Describe the bug**
if we raise req for archive user count is updating but no records are there to approve or reject

**To Reproduce**

**Expected behavior**
it should show the records 
**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/b97aa5b1-718a-43dd-8374-9528a6b5948c)

**Comment by pankajsparihar** [comment]
This feature is working fine , we just need to add our email in ApproverList# 's mail_to section.
