### ISSUE TITLE
DPU: Issue in Printing Evaluation Report - Type of Evaluation: General Evaluation

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#98]
**Describe the bug**
Upon generating an evaluation report for DePaul University (DPU) there are printing issues in the report 

**Scope of the bug**
**DPU> Degree of evaluation: UG and PG> Type of Evaluation: General Evaluation  > Evaluation Report** 

**Steps to Reproduce**
Select DePaul University (DPU) as the organization.
Enter the following details:
Evaluation Level: Global Graduate Courses
Degree of Evaluation: Undergraduate and Postgraduate
Type of Evaluation: General Evaluation
Ug Country: Ghana
Ug Scale: Letter Grade Scale (A, A-, B+, B, C+, C, D, E, F)
US Degree Equivalency: US bachelor's degree

Pg Country: Ghana
Pg Scale: Letter Grade Scale (A, A-, B+, B, C+, C, D, E, F)
US Degree Equivalency: Two years of undergraduate study
Click on "Preview" to generate the evaluation report.

**Expected Behavior**
The evaluation report should accurately reflect the selected parameters.
The report should display the correct equivalencies for both undergraduate and postgraduate evaluations.
The report should include the bachelor's GPA.

**Actual Behavior**
The evaluation report is inaccurate.
"One year of undergraduate study" is repeated and printed in postgraduate equivalency.
Bachelor's GPA is missing from the report.

Screenshots
![-80ISSUE33](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/5589bf54-f59a-47f4-b8d5-3cd80b9c02b7)
![2024-05-13 20_27_06-80isssss3](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/3faa0f6e-9fa0-4218-adb8-018ae8c6974d)
![80isssss](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/68762ed3-fee4-434b-bd27-43d35b22098a)
![issue in evaluation report 80](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/3f417aba-2eec-4814-a574-89ab3d572551)
![80ISSUE33](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/6e3c99cf-6e8e-4842-9423-4aa1befe6643)

**Comment by ipankajparihar** [comment]
resolved the problem in Organisation# ge_gr_ugpg_html

**Comment by NavnathGunjal7** [comment]
@Adnan-shariff  please test and verify

**Comment by Adnan-shariff** [comment]
working as intended on dev. 
![2024-06-20 19_23_37-Cred Eval Bridge](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/d22cdb05-e46e-410a-8855-b41e12670c43)
![2024-06-20 19_23_29-Cred Eval Bridge](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/455c5b26-1e00-482c-98b4-b443ccaf23a3)
![2024-06-20 19_23_19-Cred Eval Bridge](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/d8ca0b44-1179-4b53-8f61-0848d808710b)
