### ISSUE TITLE
Inaccurate Data Saving with Leading or Trailing Spaces in Text Fields

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#99]
**Describe the bug**
The text fields are allowing data with leading or trailing spaces to be saved, which is causing inconsistencies in generated evaluation reports.

**Scope of the bug**
Input Textfields

**To Reproduce**
Enter data with leading or trailing spaces in any text field.
Save the entered data.

**Expected behavior**
Data entered with leading or trailing spaces should be automatically trimmed before saving.

**Actual Behavior**
Data with leading or trailing spaces is saved without being trimmed, leading to inconsistencies in reports.

**Screenshots**
![spaces1](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/06de7925-3950-4fe8-9c67-77d6c7156d40)
![spaces1n](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/d1142e1d-7569-412c-8803-26d7d5fe34fe)

![spaces2n](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/f4cb3e4c-73cb-4d0a-8b2e-893d059915be)
![spaces3](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/a6f5299f-17ae-4bc7-9e63-4836db684730)
![spaces3nn](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/93299167-0dd8-46d1-9d94-9f31c25b312e)

**Comment by MSGlobalShala** [comment]
Either it is resolved or it will be resolve in N Degree
https://app.asana.com/0/1206431591540267/1207578558543495
